// src/main/webapp/app/entities/grupo-semillero/grupo-semillero.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.grupoSemillero.home.title')" id="grupo-semillero-heading">Grupo Semilleros</span>
            <router-link :to="{name: 'GrupoSemilleroCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-grupo-semillero">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.grupoSemillero.home.createLabel')">
                    Create a new Grupo Semillero
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && grupoSemilleros && grupoSemilleros.length === 0">
            <span v-text="$t('ciecytApp.grupoSemillero.home.notFound')">No grupoSemilleros found</span>
        </div>
        <div class="table-responsive" v-if="grupoSemilleros && grupoSemilleros.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('nombre')"><span v-text="$t('ciecytApp.grupoSemillero.nombre')">Nombre</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('tipo')"><span v-text="$t('ciecytApp.grupoSemillero.tipo')">Tipo</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="grupoSemillero in grupoSemilleros"
                    :key="grupoSemillero.id">
                    <td>
                        <router-link :to="{name: 'GrupoSemilleroView', params: {grupoSemilleroId: grupoSemillero.id}}">{{grupoSemillero.id}}</router-link>
                    </td>
                    <td>{{grupoSemillero.nombre}}</td>
                    <td>{{grupoSemillero.tipo}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'GrupoSemilleroView', params: {grupoSemilleroId: grupoSemillero.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'GrupoSemilleroEdit', params: {grupoSemilleroId: grupoSemillero.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(grupoSemillero)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.grupoSemillero.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-grupoSemillero-heading" v-bind:title="$t('ciecytApp.grupoSemillero.delete.question')">Are you sure you want to delete this Grupo Semillero?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-grupoSemillero" v-text="$t('entity.action.delete')" v-on:click="removeGrupoSemillero()">Delete</button>
            </div>
        </b-modal>
        <div v-show="grupoSemilleros && grupoSemilleros.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./grupo-semillero.component.ts">
</script>

// src/main/webapp/app/entities/grupo-semillero/grupo-semillero.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IGrupoSemillero } from 'app/shared/model/grupo-semillero.model';
import { AccountService } from 'app/core';
import { GrupoSemilleroService } from './grupo-semillero.service';

@Component({
  selector: 'jhi-grupo-semillero',
  templateUrl: './grupo-semillero.component.html'
})
export class GrupoSemilleroComponent implements OnInit, OnDestroy {
  grupoSemilleros: IGrupoSemillero[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected grupoSemilleroService: GrupoSemilleroService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.grupoSemilleroService
      .query()
      .pipe(
        filter((res: HttpResponse<IGrupoSemillero[]>) => res.ok),
        map((res: HttpResponse<IGrupoSemillero[]>) => res.body)
      )
      .subscribe(
        (res: IGrupoSemillero[]) => {
          this.grupoSemilleros = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInGrupoSemilleros();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IGrupoSemillero) {
    return item.id;
  }

  registerChangeInGrupoSemilleros() {
    this.eventSubscriber = this.eventManager.subscribe('grupoSemilleroListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.grupoSemillero.home.title">Grupo Semilleros</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-grupo-semillero" [routerLink]="['/grupo-semillero/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.grupoSemillero.home.createLabel">
            Create new Grupo Semillero
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="grupoSemilleros">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.grupoSemillero.nombre">Nombre</span></th>
            <th><span jhiTranslate="ciecytApp.grupoSemillero.tipo">Tipo</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let grupoSemillero of grupoSemilleros ;trackBy: trackId">
                <td><a [routerLink]="['/grupo-semillero', grupoSemillero.id, 'view' ]">{{grupoSemillero.id}}</a></td>
                <td>{{grupoSemillero.nombre}}</td>
                <td>{{grupoSemillero.tipo}}</td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/grupo-semillero', grupoSemillero.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/grupo-semillero', grupoSemillero.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'grupo-semillero', { outlets: { popup: grupoSemillero.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
