// src/main/webapp/app/entities/grupo-semillero/grupo-semillero-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { IGrupoSemillero, GrupoSemillero } from 'app/shared/model/grupo-semillero.model';
import { GrupoSemilleroService } from './grupo-semillero.service';

@Component({
  selector: 'jhi-grupo-semillero-update',
  templateUrl: './grupo-semillero-update.component.html'
})
export class GrupoSemilleroUpdateComponent implements OnInit {
  grupoSemillero: IGrupoSemillero;
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    nombre: [],
    tipo: []
  });

  constructor(protected grupoSemilleroService: GrupoSemilleroService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ grupoSemillero }) => {
      this.updateForm(grupoSemillero);
      this.grupoSemillero = grupoSemillero;
    });
  }

  updateForm(grupoSemillero: IGrupoSemillero) {
    this.editForm.patchValue({
      id: grupoSemillero.id,
      nombre: grupoSemillero.nombre,
      tipo: grupoSemillero.tipo
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const grupoSemillero = this.createFromForm();
    if (grupoSemillero.id !== undefined) {
      this.subscribeToSaveResponse(this.grupoSemilleroService.update(grupoSemillero));
    } else {
      this.subscribeToSaveResponse(this.grupoSemilleroService.create(grupoSemillero));
    }
  }

  private createFromForm(): IGrupoSemillero {
    const entity = {
      ...new GrupoSemillero(),
      id: this.editForm.get(['id']).value,
      nombre: this.editForm.get(['nombre']).value,
      tipo: this.editForm.get(['tipo']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IGrupoSemillero>>) {
    result.subscribe((res: HttpResponse<IGrupoSemillero>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-grupo-semillero-heading" jhiTranslate="ciecytApp.grupoSemillero.home.createOrEditLabel">Create or edit a Grupo Semillero</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!grupoSemillero.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.grupoSemillero.nombre" for="field_nombre">Nombre</label>
                    <input type="text" class="form-control" name="nombre" id="field_nombre"
                           formControlName="nombre"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.grupoSemillero.tipo" for="field_tipo">Tipo</label>
                    <input type="checkbox" class="form-control" name="tipo" id="field_tipo"
                           formControlName="tipo"/>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/grupo-semillero/grupo-semillero-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.grupoSemillero.home.createOrEditLabel" v-text="$t('ciecytApp.grupoSemillero.home.createOrEditLabel')">Create or edit a GrupoSemillero</h2>
                <div>
                    <div class="form-group" v-if="grupoSemillero.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="grupoSemillero.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.grupoSemillero.nombre')" for="grupo-semillero-nombre">Nombre</label>
                        <input type="text" class="form-control" name="nombre" id="grupo-semillero-nombre"
                            :class="{'valid': !$v.grupoSemillero.nombre.$invalid, 'invalid': $v.grupoSemillero.nombre.$invalid }" v-model="$v.grupoSemillero.nombre.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.grupoSemillero.tipo')" for="grupo-semillero-tipo">Tipo</label>
                        <input type="checkbox" class="form-check" name="tipo" id="grupo-semillero-tipo"
                            :class="{'valid': !$v.grupoSemillero.tipo.$invalid, 'invalid': $v.grupoSemillero.tipo.$invalid }" v-model="$v.grupoSemillero.tipo.$model" />
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.grupoSemillero.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./grupo-semillero-update.component.ts">
</script>
