// src/main/webapp/app/entities/facultad/facultad.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IFacultad } from 'app/shared/model/facultad.model';
import { AccountService } from 'app/core';
import { FacultadService } from './facultad.service';

@Component({
  selector: 'jhi-facultad',
  templateUrl: './facultad.component.html'
})
export class FacultadComponent implements OnInit, OnDestroy {
  facultads: IFacultad[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected facultadService: FacultadService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.facultadService
      .query()
      .pipe(
        filter((res: HttpResponse<IFacultad[]>) => res.ok),
        map((res: HttpResponse<IFacultad[]>) => res.body)
      )
      .subscribe(
        (res: IFacultad[]) => {
          this.facultads = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInFacultads();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IFacultad) {
    return item.id;
  }

  registerChangeInFacultads() {
    this.eventSubscriber = this.eventManager.subscribe('facultadListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.facultad.home.title">Facultads</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-facultad" [routerLink]="['/facultad/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.facultad.home.createLabel">
            Create new Facultad
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="facultads">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.facultad.nombre">Nombre</span></th>
            <th><span jhiTranslate="ciecytApp.facultad.padre">Padre</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let facultad of facultads ;trackBy: trackId">
                <td><a [routerLink]="['/facultad', facultad.id, 'view' ]">{{facultad.id}}</a></td>
                <td>{{facultad.nombre}}</td>
                <td>
                    <div *ngIf="facultad.padre">
                        <a [routerLink]="['../facultad', facultad.padre?.id, 'view' ]" >{{facultad.padre?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/facultad', facultad.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/facultad', facultad.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'facultad', { outlets: { popup: facultad.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/facultad/facultad.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.facultad.home.title')" id="facultad-heading"></span>
            <router-link custom v-slot="{ navigate }" :to="{name: 'FacultadCreate'}"><button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-facultad" @click="navigate">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.facultad.home.createLabel')"></span>
            </button></router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && facultads && facultads.length === 0">
            <span v-text="$t('ciecytApp.general.notFound')"></span>
        </div>
        <div class="table-responsive" v-if="facultads && facultads.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('codigoFacultad')"><span v-text="$t('ciecytApp.facultad.codigoFacultad')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('facultad')"><span v-text="$t('ciecytApp.facultad.facultad')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="facultad in facultads"
                    :key="facultad.id">
                    <td>
                        <router-link :to="{name: 'FacultadView', params: {facultadId: facultad.id}}">{{facultad.id}}</router-link>
                    </td>
                    <td>{{facultad.codigoFacultad}}</td>
                    <td>{{facultad.facultad}}</td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link custom v-slot="{ navigate }" :to="{name: 'FacultadView', params: {facultadId: facultad.id}}"><button class="btn btn-info btn-sm details" @click="navigate">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')"></span>
                            </button></router-link>
                            <router-link custom v-slot="{ navigate }" :to="{name: 'FacultadEdit', params: {facultadId: facultad.id}}"><button class="btn btn-primary btn-sm edit" @click="navigate">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')"></span>
                            </button></router-link>
                            <b-button v-on:click="prepareRemove(facultad)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')"></span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <template #modal-title>
<span ><span id="ciecytApp.facultad.delete.question" v-text="$t('entity.delete.title')"></span></span>
</template>
            <div class="modal-body">
                <p id="jhi-delete-facultad-heading" v-bind:title="$t('ciecytApp.facultad.delete.question')">Are you sure you want to delete this Facultad?</p>
            </div>
            <template #modal-footer>
<div >
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()"></button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-facultad" v-text="$t('entity.action.delete')" v-on:click="removeFacultad()"></button>
            </div>
</template>
        </b-modal>
        <div v-show="facultads && facultads.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./facultad.component.ts">
</script>
