// src/main/webapp/app/entities/resultados-esperados/resultados-esperados.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IResultadosEsperados } from 'app/shared/model/resultados-esperados.model';
import { AccountService } from 'app/core';
import { ResultadosEsperadosService } from './resultados-esperados.service';

@Component({
  selector: 'jhi-resultados-esperados',
  templateUrl: './resultados-esperados.component.html'
})
export class ResultadosEsperadosComponent implements OnInit, OnDestroy {
  resultadosEsperados: IResultadosEsperados[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected resultadosEsperadosService: ResultadosEsperadosService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.resultadosEsperadosService
      .query()
      .pipe(
        filter((res: HttpResponse<IResultadosEsperados[]>) => res.ok),
        map((res: HttpResponse<IResultadosEsperados[]>) => res.body)
      )
      .subscribe(
        (res: IResultadosEsperados[]) => {
          this.resultadosEsperados = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInResultadosEsperados();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IResultadosEsperados) {
    return item.id;
  }

  registerChangeInResultadosEsperados() {
    this.eventSubscriber = this.eventManager.subscribe('resultadosEsperadosListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.resultadosEsperados.home.title">Resultados Esperados</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-resultados-esperados" [routerLink]="['/resultados-esperados/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.resultadosEsperados.home.createLabel">
            Create new Resultados Esperados
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="resultadosEsperados">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.resultadosEsperados.resultado">Resultado</span></th>
            <th><span jhiTranslate="ciecytApp.resultadosEsperados.indicador">Indicador</span></th>
            <th><span jhiTranslate="ciecytApp.resultadosEsperados.beneficiario">Beneficiario</span></th>
            <th><span jhiTranslate="ciecytApp.resultadosEsperados.proyecto">Proyecto</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let resultadosEsperados of resultadosEsperados ;trackBy: trackId">
                <td><a [routerLink]="['/resultados-esperados', resultadosEsperados.id, 'view' ]">{{resultadosEsperados.id}}</a></td>
                <td>{{resultadosEsperados.resultado}}</td>
                <td>{{resultadosEsperados.indicador}}</td>
                <td>{{resultadosEsperados.beneficiario}}</td>
                <td>
                    <div *ngIf="resultadosEsperados.proyecto">
                        <a [routerLink]="['../proyecto', resultadosEsperados.proyecto?.id, 'view' ]" >{{resultadosEsperados.proyecto?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/resultados-esperados', resultadosEsperados.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/resultados-esperados', resultadosEsperados.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'resultados-esperados', { outlets: { popup: resultadosEsperados.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/resultados-esperados/resultados-esperados.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.resultadosEsperados.home.title')" id="resultados-esperados-heading">Resultados Esperados</span>
            <router-link :to="{name: 'ResultadosEsperadosCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-resultados-esperados">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.resultadosEsperados.home.createLabel')">
                    Create a new Resultados Esperados
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && resultadosEsperados && resultadosEsperados.length === 0">
            <span v-text="$t('ciecytApp.resultadosEsperados.home.notFound')">No resultadosEsperados found</span>
        </div>
        <div class="table-responsive" v-if="resultadosEsperados && resultadosEsperados.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('resultado')"><span v-text="$t('ciecytApp.resultadosEsperados.resultado')">Resultado</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('indicador')"><span v-text="$t('ciecytApp.resultadosEsperados.indicador')">Indicador</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('beneficiario')"><span v-text="$t('ciecytApp.resultadosEsperados.beneficiario')">Beneficiario</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('ordenVista')"><span v-text="$t('ciecytApp.resultadosEsperados.ordenVista')">Orden Vista</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('resultadosEsperadosProyectoTitulo')"><span v-text="$t('ciecytApp.resultadosEsperados.resultadosEsperadosProyecto')">Resultados Esperados Proyecto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="resultadosEsperados in resultadosEsperados"
                    :key="resultadosEsperados.id">
                    <td>
                        <router-link :to="{name: 'ResultadosEsperadosView', params: {resultadosEsperadosId: resultadosEsperados.id}}">{{resultadosEsperados.id}}</router-link>
                    </td>
                    <td>{{resultadosEsperados.resultado}}</td>
                    <td>{{resultadosEsperados.indicador}}</td>
                    <td>{{resultadosEsperados.beneficiario}}</td>
                    <td>{{resultadosEsperados.ordenVista}}</td>
                    <td>
                        <div v-if="resultadosEsperados.resultadosEsperadosProyectoId">
                            <router-link :to="{name: 'ProyectoView', params: {resultadosEsperadosProyectoId: resultadosEsperados.resultadosEsperadosProyectoId}}">{{resultadosEsperados.resultadosEsperadosProyectoTitulo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'ResultadosEsperadosView', params: {resultadosEsperadosId: resultadosEsperados.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'ResultadosEsperadosEdit', params: {resultadosEsperadosId: resultadosEsperados.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(resultadosEsperados)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.resultadosEsperados.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-resultadosEsperados-heading" v-bind:title="$t('ciecytApp.resultadosEsperados.delete.question')">Are you sure you want to delete this Resultados Esperados?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-resultadosEsperados" v-text="$t('entity.action.delete')" v-on:click="removeResultadosEsperados()">Delete</button>
            </div>
        </b-modal>
        <div v-show="resultadosEsperados && resultadosEsperados.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./resultados-esperados.component.ts">
</script>
