// src/main/webapp/app/entities/resultados-esperados/resultados-esperados-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IResultadosEsperados, ResultadosEsperados } from 'app/shared/model/resultados-esperados.model';
import { ResultadosEsperadosService } from './resultados-esperados.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';

@Component({
  selector: 'jhi-resultados-esperados-update',
  templateUrl: './resultados-esperados-update.component.html'
})
export class ResultadosEsperadosUpdateComponent implements OnInit {
  resultadosEsperados: IResultadosEsperados;
  isSaving: boolean;

  proyectos: IProyecto[];

  editForm = this.fb.group({
    id: [],
    resultado: [],
    indicador: [],
    beneficiario: [],
    proyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected resultadosEsperadosService: ResultadosEsperadosService,
    protected proyectoService: ProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ resultadosEsperados }) => {
      this.updateForm(resultadosEsperados);
      this.resultadosEsperados = resultadosEsperados;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(resultadosEsperados: IResultadosEsperados) {
    this.editForm.patchValue({
      id: resultadosEsperados.id,
      resultado: resultadosEsperados.resultado,
      indicador: resultadosEsperados.indicador,
      beneficiario: resultadosEsperados.beneficiario,
      proyecto: resultadosEsperados.proyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const resultadosEsperados = this.createFromForm();
    if (resultadosEsperados.id !== undefined) {
      this.subscribeToSaveResponse(this.resultadosEsperadosService.update(resultadosEsperados));
    } else {
      this.subscribeToSaveResponse(this.resultadosEsperadosService.create(resultadosEsperados));
    }
  }

  private createFromForm(): IResultadosEsperados {
    const entity = {
      ...new ResultadosEsperados(),
      id: this.editForm.get(['id']).value,
      resultado: this.editForm.get(['resultado']).value,
      indicador: this.editForm.get(['indicador']).value,
      beneficiario: this.editForm.get(['beneficiario']).value,
      proyecto: this.editForm.get(['proyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IResultadosEsperados>>) {
    result.subscribe((res: HttpResponse<IResultadosEsperados>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-resultados-esperados-heading" jhiTranslate="ciecytApp.resultadosEsperados.home.createOrEditLabel">Create or edit a Resultados Esperados</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!resultadosEsperados.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.resultadosEsperados.resultado" for="field_resultado">Resultado</label>
                    <input type="text" class="form-control" name="resultado" id="field_resultado"
                           formControlName="resultado"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.resultadosEsperados.indicador" for="field_indicador">Indicador</label>
                    <input type="text" class="form-control" name="indicador" id="field_indicador"
                           formControlName="indicador"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.resultadosEsperados.beneficiario" for="field_beneficiario">Beneficiario</label>
                    <input type="text" class="form-control" name="beneficiario" id="field_beneficiario"
                           formControlName="beneficiario"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.resultadosEsperados.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/resultados-esperados/resultados-esperados-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.resultadosEsperados.home.createOrEditLabel" v-text="$t('ciecytApp.resultadosEsperados.home.createOrEditLabel')">Create or edit a ResultadosEsperados</h2>
                <div>
                    <div class="form-group" v-if="resultadosEsperados.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="resultadosEsperados.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.resultadosEsperados.resultado')" for="resultados-esperados-resultado">Resultado</label>
                        <input type="text" class="form-control" name="resultado" id="resultados-esperados-resultado"
                            :class="{'valid': !$v.resultadosEsperados.resultado.$invalid, 'invalid': $v.resultadosEsperados.resultado.$invalid }" v-model="$v.resultadosEsperados.resultado.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.resultadosEsperados.indicador')" for="resultados-esperados-indicador">Indicador</label>
                        <input type="text" class="form-control" name="indicador" id="resultados-esperados-indicador"
                            :class="{'valid': !$v.resultadosEsperados.indicador.$invalid, 'invalid': $v.resultadosEsperados.indicador.$invalid }" v-model="$v.resultadosEsperados.indicador.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.resultadosEsperados.beneficiario')" for="resultados-esperados-beneficiario">Beneficiario</label>
                        <input type="text" class="form-control" name="beneficiario" id="resultados-esperados-beneficiario"
                            :class="{'valid': !$v.resultadosEsperados.beneficiario.$invalid, 'invalid': $v.resultadosEsperados.beneficiario.$invalid }" v-model="$v.resultadosEsperados.beneficiario.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.resultadosEsperados.ordenVista')" for="resultados-esperados-ordenVista">Orden Vista</label>
                        <input type="number" class="form-control" name="ordenVista" id="resultados-esperados-ordenVista"
                            :class="{'valid': !$v.resultadosEsperados.ordenVista.$invalid, 'invalid': $v.resultadosEsperados.ordenVista.$invalid }" v-model.number="$v.resultadosEsperados.ordenVista.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.resultadosEsperados.resultadosEsperadosProyecto')" for="resultados-esperados-resultadosEsperadosProyecto">Resultados Esperados Proyecto</label>
                        <select class="form-control" id="resultados-esperados-resultadosEsperadosProyecto" name="resultadosEsperadosProyecto" v-model="resultadosEsperados.resultadosEsperadosProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.resultadosEsperados.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./resultados-esperados-update.component.ts">
</script>
