// src/main/webapp/app/entities/entidad-financiadora/entidad-financiadora-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IEntidadFinanciadora, EntidadFinanciadora } from 'app/shared/model/entidad-financiadora.model';
import { EntidadFinanciadoraService } from './entidad-financiadora.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';

@Component({
  selector: 'jhi-entidad-financiadora-update',
  templateUrl: './entidad-financiadora-update.component.html'
})
export class EntidadFinanciadoraUpdateComponent implements OnInit {
  entidadFinanciadora: IEntidadFinanciadora;
  isSaving: boolean;

  proyectos: IProyecto[];

  editForm = this.fb.group({
    id: [],
    valor: [],
    estadoFinanciacion: [],
    proyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected entidadFinanciadoraService: EntidadFinanciadoraService,
    protected proyectoService: ProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ entidadFinanciadora }) => {
      this.updateForm(entidadFinanciadora);
      this.entidadFinanciadora = entidadFinanciadora;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(entidadFinanciadora: IEntidadFinanciadora) {
    this.editForm.patchValue({
      id: entidadFinanciadora.id,
      valor: entidadFinanciadora.valor,
      estadoFinanciacion: entidadFinanciadora.estadoFinanciacion,
      proyecto: entidadFinanciadora.proyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const entidadFinanciadora = this.createFromForm();
    if (entidadFinanciadora.id !== undefined) {
      this.subscribeToSaveResponse(this.entidadFinanciadoraService.update(entidadFinanciadora));
    } else {
      this.subscribeToSaveResponse(this.entidadFinanciadoraService.create(entidadFinanciadora));
    }
  }

  private createFromForm(): IEntidadFinanciadora {
    const entity = {
      ...new EntidadFinanciadora(),
      id: this.editForm.get(['id']).value,
      valor: this.editForm.get(['valor']).value,
      estadoFinanciacion: this.editForm.get(['estadoFinanciacion']).value,
      proyecto: this.editForm.get(['proyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IEntidadFinanciadora>>) {
    result.subscribe((res: HttpResponse<IEntidadFinanciadora>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-entidad-financiadora-heading" jhiTranslate="ciecytApp.entidadFinanciadora.home.createOrEditLabel">Create or edit a Entidad Financiadora</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!entidadFinanciadora.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.entidadFinanciadora.valor" for="field_valor">Valor</label>
                    <input type="number" class="form-control" name="valor" id="field_valor"
                           formControlName="valor"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.entidadFinanciadora.estadoFinanciacion" for="field_estadoFinanciacion">Estado Financiacion</label>
                    <input type="checkbox" class="form-control" name="estadoFinanciacion" id="field_estadoFinanciacion"
                           formControlName="estadoFinanciacion"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.entidadFinanciadora.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/entidad-financiadora/entidad-financiadora-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.entidadFinanciadora.home.createOrEditLabel" v-text="$t('ciecytApp.entidadFinanciadora.home.createOrEditLabel')">Create or edit a EntidadFinanciadora</h2>
                <div>
                    <div class="form-group" v-if="entidadFinanciadora.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="entidadFinanciadora.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.entidadFinanciadora.valor')" for="entidad-financiadora-valor">Valor</label>
                        <input type="number" class="form-control" name="valor" id="entidad-financiadora-valor"
                            :class="{'valid': !$v.entidadFinanciadora.valor.$invalid, 'invalid': $v.entidadFinanciadora.valor.$invalid }" v-model.number="$v.entidadFinanciadora.valor.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.entidadFinanciadora.aprobada')" for="entidad-financiadora-aprobada">Aprobada</label>
                        <input type="checkbox" class="form-check" name="aprobada" id="entidad-financiadora-aprobada"
                            :class="{'valid': !$v.entidadFinanciadora.aprobada.$invalid, 'invalid': $v.entidadFinanciadora.aprobada.$invalid }" v-model="$v.entidadFinanciadora.aprobada.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.entidadFinanciadora.entidadFinanciadoraEntidad')" for="entidad-financiadora-entidadFinanciadoraEntidad">Entidad Financiadora Entidad</label>
                        <select class="form-control" id="entidad-financiadora-entidadFinanciadoraEntidad" name="entidadFinanciadoraEntidad" v-model="entidadFinanciadora.entidadFinanciadoraEntidadId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="entidadOption.id" v-for="entidadOption in entidads" :key="entidadOption.id">{{entidadOption.entidad}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.entidadFinanciadora.entidadFinanciadoraProyecto')" for="entidad-financiadora-entidadFinanciadoraProyecto">Entidad Financiadora Proyecto</label>
                        <select class="form-control" id="entidad-financiadora-entidadFinanciadoraProyecto" name="entidadFinanciadoraProyecto" v-model="entidadFinanciadora.entidadFinanciadoraProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.entidadFinanciadora.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./entidad-financiadora-update.component.ts">
</script>
