// src/main/webapp/app/entities/ficha-tecnica/ficha-tecnica-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.fichaTecnica.home.createOrEditLabel" v-text="$t('ciecytApp.fichaTecnica.home.createOrEditLabel')">Create or edit a FichaTecnica</h2>
                <div>
                    <div class="form-group" v-if="fichaTecnica.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="fichaTecnica.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.fichaTecnica.tituloProfesional')" for="ficha-tecnica-tituloProfesional">Titulo Profesional</label>
                        <input type="text" class="form-control" name="tituloProfesional" id="ficha-tecnica-tituloProfesional"
                            :class="{'valid': !$v.fichaTecnica.tituloProfesional.$invalid, 'invalid': $v.fichaTecnica.tituloProfesional.$invalid }" v-model="$v.fichaTecnica.tituloProfesional.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.fichaTecnica.tituloPostgrado')" for="ficha-tecnica-tituloPostgrado">Titulo Postgrado</label>
                        <input type="text" class="form-control" name="tituloPostgrado" id="ficha-tecnica-tituloPostgrado"
                            :class="{'valid': !$v.fichaTecnica.tituloPostgrado.$invalid, 'invalid': $v.fichaTecnica.tituloPostgrado.$invalid }" v-model="$v.fichaTecnica.tituloPostgrado.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.fichaTecnica.experiencia')" for="ficha-tecnica-experiencia">Experiencia</label>
                        <input type="text" class="form-control" name="experiencia" id="ficha-tecnica-experiencia"
                            :class="{'valid': !$v.fichaTecnica.experiencia.$invalid, 'invalid': $v.fichaTecnica.experiencia.$invalid }" v-model="$v.fichaTecnica.experiencia.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.fichaTecnica.fichaTecnicaUser')" for="ficha-tecnica-fichaTecnicaUser">Ficha Tecnica User</label>
                        <select class="form-control" id="ficha-tecnica-fichaTecnicaUser" name="fichaTecnicaUser" v-model="fichaTecnica.fichaTecnicaUserId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="userOption.id" v-for="userOption in users" :key="userOption.id">{{userOption.login}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.fichaTecnica.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./ficha-tecnica-update.component.ts">
</script>

// src/main/webapp/app/entities/ficha-tecnica/ficha-tecnica-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IFichaTecnica, FichaTecnica } from 'app/shared/model/ficha-tecnica.model';
import { FichaTecnicaService } from './ficha-tecnica.service';
import { IUser, UserService } from 'app/core';

@Component({
  selector: 'jhi-ficha-tecnica-update',
  templateUrl: './ficha-tecnica-update.component.html'
})
export class FichaTecnicaUpdateComponent implements OnInit {
  fichaTecnica: IFichaTecnica;
  isSaving: boolean;

  users: IUser[];

  editForm = this.fb.group({
    id: [],
    tituloProfecional: [],
    tituloPosgrado: [],
    experencia: [],
    user: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected fichaTecnicaService: FichaTecnicaService,
    protected userService: UserService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ fichaTecnica }) => {
      this.updateForm(fichaTecnica);
      this.fichaTecnica = fichaTecnica;
    });
    this.userService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IUser[]>) => mayBeOk.ok),
        map((response: HttpResponse<IUser[]>) => response.body)
      )
      .subscribe((res: IUser[]) => (this.users = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(fichaTecnica: IFichaTecnica) {
    this.editForm.patchValue({
      id: fichaTecnica.id,
      tituloProfecional: fichaTecnica.tituloProfecional,
      tituloPosgrado: fichaTecnica.tituloPosgrado,
      experencia: fichaTecnica.experencia,
      user: fichaTecnica.user
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const fichaTecnica = this.createFromForm();
    if (fichaTecnica.id !== undefined) {
      this.subscribeToSaveResponse(this.fichaTecnicaService.update(fichaTecnica));
    } else {
      this.subscribeToSaveResponse(this.fichaTecnicaService.create(fichaTecnica));
    }
  }

  private createFromForm(): IFichaTecnica {
    const entity = {
      ...new FichaTecnica(),
      id: this.editForm.get(['id']).value,
      tituloProfecional: this.editForm.get(['tituloProfecional']).value,
      tituloPosgrado: this.editForm.get(['tituloPosgrado']).value,
      experencia: this.editForm.get(['experencia']).value,
      user: this.editForm.get(['user']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IFichaTecnica>>) {
    result.subscribe((res: HttpResponse<IFichaTecnica>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackUserById(index: number, item: IUser) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-ficha-tecnica-heading" jhiTranslate="ciecytApp.fichaTecnica.home.createOrEditLabel">Create or edit a Ficha Tecnica</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!fichaTecnica.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.fichaTecnica.tituloProfecional" for="field_tituloProfecional">Titulo Profecional</label>
                    <input type="text" class="form-control" name="tituloProfecional" id="field_tituloProfecional"
                           formControlName="tituloProfecional"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.fichaTecnica.tituloPosgrado" for="field_tituloPosgrado">Titulo Posgrado</label>
                    <input type="text" class="form-control" name="tituloPosgrado" id="field_tituloPosgrado"
                           formControlName="tituloPosgrado"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.fichaTecnica.experencia" for="field_experencia">Experencia</label>
                    <input type="text" class="form-control" name="experencia" id="field_experencia"
                           formControlName="experencia"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.fichaTecnica.user" for="field_user">User</label>
                    <select class="form-control" id="field_user" name="user" formControlName="user">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="userOption.id === editForm.get('user').value?.id ? editForm.get('user').value : userOption" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
