// src/main/webapp/app/entities/ficha-tecnica/ficha-tecnica.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IFichaTecnica } from 'app/shared/model/ficha-tecnica.model';
import { AccountService } from 'app/core';
import { FichaTecnicaService } from './ficha-tecnica.service';

@Component({
  selector: 'jhi-ficha-tecnica',
  templateUrl: './ficha-tecnica.component.html'
})
export class FichaTecnicaComponent implements OnInit, OnDestroy {
  fichaTecnicas: IFichaTecnica[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected fichaTecnicaService: FichaTecnicaService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.fichaTecnicaService
      .query()
      .pipe(
        filter((res: HttpResponse<IFichaTecnica[]>) => res.ok),
        map((res: HttpResponse<IFichaTecnica[]>) => res.body)
      )
      .subscribe(
        (res: IFichaTecnica[]) => {
          this.fichaTecnicas = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInFichaTecnicas();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IFichaTecnica) {
    return item.id;
  }

  registerChangeInFichaTecnicas() {
    this.eventSubscriber = this.eventManager.subscribe('fichaTecnicaListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.fichaTecnica.home.title">Ficha Tecnicas</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-ficha-tecnica" [routerLink]="['/ficha-tecnica/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.fichaTecnica.home.createLabel">
            Create new Ficha Tecnica
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="fichaTecnicas">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.fichaTecnica.tituloProfecional">Titulo Profecional</span></th>
            <th><span jhiTranslate="ciecytApp.fichaTecnica.tituloPosgrado">Titulo Posgrado</span></th>
            <th><span jhiTranslate="ciecytApp.fichaTecnica.experencia">Experencia</span></th>
            <th><span jhiTranslate="ciecytApp.fichaTecnica.user">User</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let fichaTecnica of fichaTecnicas ;trackBy: trackId">
                <td><a [routerLink]="['/ficha-tecnica', fichaTecnica.id, 'view' ]">{{fichaTecnica.id}}</a></td>
                <td>{{fichaTecnica.tituloProfecional}}</td>
                <td>{{fichaTecnica.tituloPosgrado}}</td>
                <td>{{fichaTecnica.experencia}}</td>
                <td>
                    {{fichaTecnica.user?.login}}
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/ficha-tecnica', fichaTecnica.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/ficha-tecnica', fichaTecnica.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'ficha-tecnica', { outlets: { popup: fichaTecnica.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/ficha-tecnica/ficha-tecnica.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.fichaTecnica.home.title')" id="ficha-tecnica-heading">Ficha Tecnicas</span>
            <router-link :to="{name: 'FichaTecnicaCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-ficha-tecnica">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.fichaTecnica.home.createLabel')">
                    Create a new Ficha Tecnica
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && fichaTecnicas && fichaTecnicas.length === 0">
            <span v-text="$t('ciecytApp.fichaTecnica.home.notFound')">No fichaTecnicas found</span>
        </div>
        <div class="table-responsive" v-if="fichaTecnicas && fichaTecnicas.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('tituloProfesional')"><span v-text="$t('ciecytApp.fichaTecnica.tituloProfesional')">Titulo Profesional</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('tituloPostgrado')"><span v-text="$t('ciecytApp.fichaTecnica.tituloPostgrado')">Titulo Postgrado</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('experiencia')"><span v-text="$t('ciecytApp.fichaTecnica.experiencia')">Experiencia</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fichaTecnicaUserLogin')"><span v-text="$t('ciecytApp.fichaTecnica.fichaTecnicaUser')">Ficha Tecnica User</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="fichaTecnica in fichaTecnicas"
                    :key="fichaTecnica.id">
                    <td>
                        <router-link :to="{name: 'FichaTecnicaView', params: {fichaTecnicaId: fichaTecnica.id}}">{{fichaTecnica.id}}</router-link>
                    </td>
                    <td>{{fichaTecnica.tituloProfesional}}</td>
                    <td>{{fichaTecnica.tituloPostgrado}}</td>
                    <td>{{fichaTecnica.experiencia}}</td>
                    <td>
                        {{fichaTecnica.fichaTecnicaUserLogin}}
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'FichaTecnicaView', params: {fichaTecnicaId: fichaTecnica.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'FichaTecnicaEdit', params: {fichaTecnicaId: fichaTecnica.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(fichaTecnica)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.fichaTecnica.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-fichaTecnica-heading" v-bind:title="$t('ciecytApp.fichaTecnica.delete.question')">Are you sure you want to delete this Ficha Tecnica?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-fichaTecnica" v-text="$t('entity.action.delete')" v-on:click="removeFichaTecnica()">Delete</button>
            </div>
        </b-modal>
        <div v-show="fichaTecnicas && fichaTecnicas.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./ficha-tecnica.component.ts">
</script>
