// src/main/webapp/app/entities/categorizacion/categorizacion-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { ICategorizacion, Categorizacion } from 'app/shared/model/categorizacion.model';
import { CategorizacionService } from './categorizacion.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';

@Component({
  selector: 'jhi-categorizacion-update',
  templateUrl: './categorizacion-update.component.html'
})
export class CategorizacionUpdateComponent implements OnInit {
  categorizacion: ICategorizacion;
  isSaving: boolean;

  proyectos: IProyecto[];

  editForm = this.fb.group({
    id: [],
    categoria: [],
    proyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected categorizacionService: CategorizacionService,
    protected proyectoService: ProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ categorizacion }) => {
      this.updateForm(categorizacion);
      this.categorizacion = categorizacion;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(categorizacion: ICategorizacion) {
    this.editForm.patchValue({
      id: categorizacion.id,
      categoria: categorizacion.categoria,
      proyecto: categorizacion.proyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const categorizacion = this.createFromForm();
    if (categorizacion.id !== undefined) {
      this.subscribeToSaveResponse(this.categorizacionService.update(categorizacion));
    } else {
      this.subscribeToSaveResponse(this.categorizacionService.create(categorizacion));
    }
  }

  private createFromForm(): ICategorizacion {
    const entity = {
      ...new Categorizacion(),
      id: this.editForm.get(['id']).value,
      categoria: this.editForm.get(['categoria']).value,
      proyecto: this.editForm.get(['proyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICategorizacion>>) {
    result.subscribe((res: HttpResponse<ICategorizacion>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-categorizacion-heading" jhiTranslate="ciecytApp.categorizacion.home.createOrEditLabel">Create or edit a Categorizacion</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!categorizacion.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.categorizacion.categoria" for="field_categoria">Categoria</label>
                    <input type="text" class="form-control" name="categoria" id="field_categoria"
                           formControlName="categoria"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.categorizacion.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/categorizacion/categorizacion-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.categorizacion.home.createOrEditLabel" v-text="$t('ciecytApp.categorizacion.home.createOrEditLabel')">Create or edit a Categorizacion</h2>
                <div>
                    <div class="mb-3 form-group" v-if="categorizacion.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="categorizacion.id" readonly />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.categorizacion.categoria')" for="categorizacion-categoria">Categoria</label>
                        <input type="text" class="form-control" name="categoria" id="categorizacion-categoria"
                            :class="{'valid': !$v.categorizacion.categoria.$invalid, 'invalid': $v.categorizacion.categoria.$invalid }" v-model="$v.categorizacion.categoria.$model" />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.categorizacion.descripcion')" for="categorizacion-descripcion">Descripcion</label>
                        <input type="text" class="form-control" name="descripcion" id="categorizacion-descripcion"
                            :class="{'valid': !$v.categorizacion.descripcion.$invalid, 'invalid': $v.categorizacion.descripcion.$invalid }" v-model="$v.categorizacion.descripcion.$model" />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.categorizacion.categorizacionProyecto')" for="categorizacion-categorizacionProyecto">Categorizacion Proyecto</label>
                        <select class="form-control" id="categorizacion-categorizacionProyecto" name="categorizacionProyecto" v-model="categorizacion.categorizacionProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.categorizacion.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./categorizacion-update.component.ts">
</script>
