// src/main/webapp/app/entities/cronograma/cronograma-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { ICronograma, Cronograma } from 'app/shared/model/cronograma.model';
import { CronogramaService } from './cronograma.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';

@Component({
  selector: 'jhi-cronograma-update',
  templateUrl: './cronograma-update.component.html'
})
export class CronogramaUpdateComponent implements OnInit {
  cronograma: ICronograma;
  isSaving: boolean;

  proyectos: IProyecto[];
  fechaIniDp: any;
  fechaFinDp: any;

  editForm = this.fb.group({
    id: [],
    actividad: [],
    duracion: [],
    fechaIni: [],
    fechaFin: [],
    proyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected cronogramaService: CronogramaService,
    protected proyectoService: ProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ cronograma }) => {
      this.updateForm(cronograma);
      this.cronograma = cronograma;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(cronograma: ICronograma) {
    this.editForm.patchValue({
      id: cronograma.id,
      actividad: cronograma.actividad,
      duracion: cronograma.duracion,
      fechaIni: cronograma.fechaIni,
      fechaFin: cronograma.fechaFin,
      proyecto: cronograma.proyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const cronograma = this.createFromForm();
    if (cronograma.id !== undefined) {
      this.subscribeToSaveResponse(this.cronogramaService.update(cronograma));
    } else {
      this.subscribeToSaveResponse(this.cronogramaService.create(cronograma));
    }
  }

  private createFromForm(): ICronograma {
    const entity = {
      ...new Cronograma(),
      id: this.editForm.get(['id']).value,
      actividad: this.editForm.get(['actividad']).value,
      duracion: this.editForm.get(['duracion']).value,
      fechaIni: this.editForm.get(['fechaIni']).value,
      fechaFin: this.editForm.get(['fechaFin']).value,
      proyecto: this.editForm.get(['proyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ICronograma>>) {
    result.subscribe((res: HttpResponse<ICronograma>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-cronograma-heading" jhiTranslate="ciecytApp.cronograma.home.createOrEditLabel">Create or edit a Cronograma</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!cronograma.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.cronograma.actividad" for="field_actividad">Actividad</label>
                    <input type="text" class="form-control" name="actividad" id="field_actividad"
                           formControlName="actividad"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.cronograma.duracion" for="field_duracion">Duracion</label>
                    <input type="number" class="form-control" name="duracion" id="field_duracion"
                           formControlName="duracion"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.cronograma.fechaIni" for="field_fechaIni">Fecha Ini</label>
                    <div class="input-group">
                        <input id="field_fechaIni" type="text" class="form-control" name="fechaIni" ngbDatepicker  #fechaIniDp="ngbDatepicker" formControlName="fechaIni"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="fechaIniDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.cronograma.fechaFin" for="field_fechaFin">Fecha Fin</label>
                    <div class="input-group">
                        <input id="field_fechaFin" type="text" class="form-control" name="fechaFin" ngbDatepicker  #fechaFinDp="ngbDatepicker" formControlName="fechaFin"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="fechaFinDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.cronograma.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/cronograma/cronograma-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.cronograma.home.createOrEditLabel" v-text="$t('ciecytApp.cronograma.home.createOrEditLabel')">Create or edit a Cronograma</h2>
                <div>
                    <div class="form-group" v-if="cronograma.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="cronograma.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.cronograma.actividad')" for="cronograma-actividad">Actividad</label>
                        <input type="text" class="form-control" name="actividad" id="cronograma-actividad"
                            :class="{'valid': !$v.cronograma.actividad.$invalid, 'invalid': $v.cronograma.actividad.$invalid }" v-model="$v.cronograma.actividad.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.cronograma.duracion')" for="cronograma-duracion">Duracion</label>
                        <input type="number" class="form-control" name="duracion" id="cronograma-duracion"
                            :class="{'valid': !$v.cronograma.duracion.$invalid, 'invalid': $v.cronograma.duracion.$invalid }" v-model.number="$v.cronograma.duracion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.cronograma.fechaInicio')" for="cronograma-fechaInicio">Fecha Inicio</label>
                        <div class="input-group">
                            <input id="cronograma-fechaInicio" type="date" class="form-control" name="fechaInicio"  :class="{'valid': !$v.cronograma.fechaInicio.$invalid, 'invalid': $v.cronograma.fechaInicio.$invalid }"
                            v-model="$v.cronograma.fechaInicio.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.cronograma.fechaFin')" for="cronograma-fechaFin">Fecha Fin</label>
                        <div class="input-group">
                            <input id="cronograma-fechaFin" type="date" class="form-control" name="fechaFin"  :class="{'valid': !$v.cronograma.fechaFin.$invalid, 'invalid': $v.cronograma.fechaFin.$invalid }"
                            v-model="$v.cronograma.fechaFin.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.cronograma.ordenVista')" for="cronograma-ordenVista">Orden Vista</label>
                        <input type="number" class="form-control" name="ordenVista" id="cronograma-ordenVista"
                            :class="{'valid': !$v.cronograma.ordenVista.$invalid, 'invalid': $v.cronograma.ordenVista.$invalid }" v-model.number="$v.cronograma.ordenVista.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.cronograma.cronogramaProyecto')" for="cronograma-cronogramaProyecto">Cronograma Proyecto</label>
                        <select class="form-control" id="cronograma-cronogramaProyecto" name="cronogramaProyecto" v-model="cronograma.cronogramaProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.cronograma.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./cronograma-update.component.ts">
</script>
