// src/main/webapp/app/entities/cronograma/cronograma.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ICronograma } from 'app/shared/model/cronograma.model';
import { AccountService } from 'app/core';
import { CronogramaService } from './cronograma.service';

@Component({
  selector: 'jhi-cronograma',
  templateUrl: './cronograma.component.html'
})
export class CronogramaComponent implements OnInit, OnDestroy {
  cronogramas: ICronograma[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected cronogramaService: CronogramaService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.cronogramaService
      .query()
      .pipe(
        filter((res: HttpResponse<ICronograma[]>) => res.ok),
        map((res: HttpResponse<ICronograma[]>) => res.body)
      )
      .subscribe(
        (res: ICronograma[]) => {
          this.cronogramas = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInCronogramas();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ICronograma) {
    return item.id;
  }

  registerChangeInCronogramas() {
    this.eventSubscriber = this.eventManager.subscribe('cronogramaListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.cronograma.home.title">Cronogramas</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-cronograma" [routerLink]="['/cronograma/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.cronograma.home.createLabel">
            Create new Cronograma
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="cronogramas">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.cronograma.actividad">Actividad</span></th>
            <th><span jhiTranslate="ciecytApp.cronograma.duracion">Duracion</span></th>
            <th><span jhiTranslate="ciecytApp.cronograma.fechaIni">Fecha Ini</span></th>
            <th><span jhiTranslate="ciecytApp.cronograma.fechaFin">Fecha Fin</span></th>
            <th><span jhiTranslate="ciecytApp.cronograma.proyecto">Proyecto</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let cronograma of cronogramas ;trackBy: trackId">
                <td><a [routerLink]="['/cronograma', cronograma.id, 'view' ]">{{cronograma.id}}</a></td>
                <td>{{cronograma.actividad}}</td>
                <td>{{cronograma.duracion}}</td>
                <td>{{cronograma.fechaIni | date:'mediumDate'}}</td>
                <td>{{cronograma.fechaFin | date:'mediumDate'}}</td>
                <td>
                    <div *ngIf="cronograma.proyecto">
                        <a [routerLink]="['../proyecto', cronograma.proyecto?.id, 'view' ]" >{{cronograma.proyecto?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/cronograma', cronograma.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/cronograma', cronograma.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'cronograma', { outlets: { popup: cronograma.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/cronograma/cronograma.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.cronograma.home.title')" id="cronograma-heading">Cronogramas</span>
            <router-link :to="{name: 'CronogramaCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-cronograma">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.cronograma.home.createLabel')">
                    Create a new Cronograma
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && cronogramas && cronogramas.length === 0">
            <span v-text="$t('ciecytApp.cronograma.home.notFound')">No cronogramas found</span>
        </div>
        <div class="table-responsive" v-if="cronogramas && cronogramas.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('actividad')"><span v-text="$t('ciecytApp.cronograma.actividad')">Actividad</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('duracion')"><span v-text="$t('ciecytApp.cronograma.duracion')">Duracion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fechaInicio')"><span v-text="$t('ciecytApp.cronograma.fechaInicio')">Fecha Inicio</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fechaFin')"><span v-text="$t('ciecytApp.cronograma.fechaFin')">Fecha Fin</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('ordenVista')"><span v-text="$t('ciecytApp.cronograma.ordenVista')">Orden Vista</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('cronogramaProyectoTitulo')"><span v-text="$t('ciecytApp.cronograma.cronogramaProyecto')">Cronograma Proyecto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="cronograma in cronogramas"
                    :key="cronograma.id">
                    <td>
                        <router-link :to="{name: 'CronogramaView', params: {cronogramaId: cronograma.id}}">{{cronograma.id}}</router-link>
                    </td>
                    <td>{{cronograma.actividad}}</td>
                    <td>{{cronograma.duracion}}</td>
                    <td>{{cronograma.fechaInicio}}</td>
                    <td>{{cronograma.fechaFin}}</td>
                    <td>{{cronograma.ordenVista}}</td>
                    <td>
                        <div v-if="cronograma.cronogramaProyectoId">
                            <router-link :to="{name: 'ProyectoView', params: {cronogramaProyectoId: cronograma.cronogramaProyectoId}}">{{cronograma.cronogramaProyectoTitulo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'CronogramaView', params: {cronogramaId: cronograma.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'CronogramaEdit', params: {cronogramaId: cronograma.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(cronograma)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.cronograma.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-cronograma-heading" v-bind:title="$t('ciecytApp.cronograma.delete.question')">Are you sure you want to delete this Cronograma?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-cronograma" v-text="$t('entity.action.delete')" v-on:click="removeCronograma()">Delete</button>
            </div>
        </b-modal>
        <div v-show="cronogramas && cronogramas.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./cronograma.component.ts">
</script>
