// src/main/webapp/app/entities/impactos-esperados/impactos-esperados.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.impactosEsperados.home.title')" id="impactos-esperados-heading"></span>
            <router-link custom v-slot="{ navigate }" :to="{name: 'ImpactosEsperadosCreate'}"><button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-impactos-esperados" @click="navigate">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.impactosEsperados.home.createLabel')"></span>
            </button></router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && impactosEsperados && impactosEsperados.length === 0">
            <span v-text="$t('ciecytApp.impactosEsperados.home.notFound')"></span>
        </div>
        <div class="table-responsive" v-if="impactosEsperados && impactosEsperados.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('impacto')"><span v-text="$t('ciecytApp.impactosEsperados.impacto')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('plazo')"><span v-text="$t('ciecytApp.impactosEsperados.plazo')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('indicador')"><span v-text="$t('ciecytApp.impactosEsperados.indicador')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('supuestos')"><span v-text="$t('ciecytApp.impactosEsperados.supuestos')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('ordenVista')"><span v-text="$t('ciecytApp.impactosEsperados.ordenVista')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('impactosEsperadoProyectoTitulo')"><span v-text="$t('ciecytApp.impactosEsperados.impactosEsperadoProyecto')"></span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="impactosEsperados in impactosEsperados"
                    :key="impactosEsperados.id">
                    <td>
                        <router-link :to="{name: 'ImpactosEsperadosView', params: {impactosEsperadosId: impactosEsperados.id}}">{{impactosEsperados.id}}</router-link>
                    </td>
                    <td>{{impactosEsperados.impacto}}</td>
                    <td>{{impactosEsperados.plazo}}</td>
                    <td>{{impactosEsperados.indicador}}</td>
                    <td>{{impactosEsperados.supuestos}}</td>
                    <td>{{impactosEsperados.ordenVista}}</td>
                    <td>
                        <div v-if="impactosEsperados.impactosEsperadoProyectoId">
                            <router-link :to="{name: 'ProyectoView', params: {impactosEsperadoProyectoId: impactosEsperados.impactosEsperadoProyectoId}}">{{impactosEsperados.impactosEsperadoProyectoTitulo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link custom v-slot="{ navigate }" :to="{name: 'ImpactosEsperadosView', params: {impactosEsperadosId: impactosEsperados.id}}"><button class="btn btn-info btn-sm details" @click="navigate">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')"></span>
                            </button></router-link>
                            <router-link custom v-slot="{ navigate }" :to="{name: 'ImpactosEsperadosEdit', params: {impactosEsperadosId: impactosEsperados.id}}"><button class="btn btn-primary btn-sm edit" @click="navigate">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')"></span>
                            </button></router-link>
                            <b-button v-on:click="prepareRemove(impactosEsperados)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')"></span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <template #modal-title>
<span ><span id="ciecytApp.impactosEsperados.delete.question" v-text="$t('entity.delete.title')"></span></span>
</template>
            <div class="modal-body">
                <p id="jhi-delete-impactosEsperados-heading" v-bind:title="$t('ciecytApp.impactosEsperados.delete.question')">Are you sure you want to delete this Impactos Esperados?</p>
            </div>
            <template #modal-footer>
<div >
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()"></button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-impactosEsperados" v-text="$t('entity.action.delete')" v-on:click="removeImpactosEsperados()"></button>
            </div>
</template>
        </b-modal>
        <div v-show="impactosEsperados && impactosEsperados.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./impactos-esperados.component.ts">
</script>

// src/main/webapp/app/entities/impactos-esperados/impactos-esperados.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IImpactosEsperados } from 'app/shared/model/impactos-esperados.model';
import { AccountService } from 'app/core';
import { ImpactosEsperadosService } from './impactos-esperados.service';

@Component({
  selector: 'jhi-impactos-esperados',
  templateUrl: './impactos-esperados.component.html'
})
export class ImpactosEsperadosComponent implements OnInit, OnDestroy {
  impactosEsperados: IImpactosEsperados[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected impactosEsperadosService: ImpactosEsperadosService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.impactosEsperadosService
      .query()
      .pipe(
        filter((res: HttpResponse<IImpactosEsperados[]>) => res.ok),
        map((res: HttpResponse<IImpactosEsperados[]>) => res.body)
      )
      .subscribe(
        (res: IImpactosEsperados[]) => {
          this.impactosEsperados = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInImpactosEsperados();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IImpactosEsperados) {
    return item.id;
  }

  registerChangeInImpactosEsperados() {
    this.eventSubscriber = this.eventManager.subscribe('impactosEsperadosListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.impactosEsperados.home.title">Impactos Esperados</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-impactos-esperados" [routerLink]="['/impactos-esperados/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.impactosEsperados.home.createLabel">
            Create new Impactos Esperados
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="impactosEsperados">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.impactosEsperados.impacto">Impacto</span></th>
            <th><span jhiTranslate="ciecytApp.impactosEsperados.plazo">Plazo</span></th>
            <th><span jhiTranslate="ciecytApp.impactosEsperados.indicador">Indicador</span></th>
            <th><span jhiTranslate="ciecytApp.impactosEsperados.supuestos">Supuestos</span></th>
            <th><span jhiTranslate="ciecytApp.impactosEsperados.proyecto">Proyecto</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let impactosEsperados of impactosEsperados ;trackBy: trackId">
                <td><a [routerLink]="['/impactos-esperados', impactosEsperados.id, 'view' ]">{{impactosEsperados.id}}</a></td>
                <td>{{impactosEsperados.impacto}}</td>
                <td>{{impactosEsperados.plazo}}</td>
                <td>{{impactosEsperados.indicador}}</td>
                <td>{{impactosEsperados.supuestos}}</td>
                <td>
                    <div *ngIf="impactosEsperados.proyecto">
                        <a [routerLink]="['../proyecto', impactosEsperados.proyecto?.id, 'view' ]" >{{impactosEsperados.proyecto?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/impactos-esperados', impactosEsperados.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/impactos-esperados', impactosEsperados.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'impactos-esperados', { outlets: { popup: impactosEsperados.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
