// src/main/webapp/app/entities/impactos-esperados/impactos-esperados-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.impactosEsperados.home.createOrEditLabel" v-text="$t('ciecytApp.impactosEsperados.home.createOrEditLabel')">Create or edit a ImpactosEsperados</h2>
                <div>
                    <div class="form-group" v-if="impactosEsperados.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="impactosEsperados.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.impactosEsperados.impacto')" for="impactos-esperados-impacto">Impacto</label>
                        <input type="text" class="form-control" name="impacto" id="impactos-esperados-impacto"
                            :class="{'valid': !$v.impactosEsperados.impacto.$invalid, 'invalid': $v.impactosEsperados.impacto.$invalid }" v-model="$v.impactosEsperados.impacto.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.impactosEsperados.plazo')" for="impactos-esperados-plazo">Plazo</label>
                        <input type="number" class="form-control" name="plazo" id="impactos-esperados-plazo"
                            :class="{'valid': !$v.impactosEsperados.plazo.$invalid, 'invalid': $v.impactosEsperados.plazo.$invalid }" v-model.number="$v.impactosEsperados.plazo.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.impactosEsperados.indicador')" for="impactos-esperados-indicador">Indicador</label>
                        <input type="text" class="form-control" name="indicador" id="impactos-esperados-indicador"
                            :class="{'valid': !$v.impactosEsperados.indicador.$invalid, 'invalid': $v.impactosEsperados.indicador.$invalid }" v-model="$v.impactosEsperados.indicador.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.impactosEsperados.supuestos')" for="impactos-esperados-supuestos">Supuestos</label>
                        <input type="text" class="form-control" name="supuestos" id="impactos-esperados-supuestos"
                            :class="{'valid': !$v.impactosEsperados.supuestos.$invalid, 'invalid': $v.impactosEsperados.supuestos.$invalid }" v-model="$v.impactosEsperados.supuestos.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.impactosEsperados.ordenVista')" for="impactos-esperados-ordenVista">Orden Vista</label>
                        <input type="number" class="form-control" name="ordenVista" id="impactos-esperados-ordenVista"
                            :class="{'valid': !$v.impactosEsperados.ordenVista.$invalid, 'invalid': $v.impactosEsperados.ordenVista.$invalid }" v-model.number="$v.impactosEsperados.ordenVista.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.impactosEsperados.impactosEsperadoProyecto')" for="impactos-esperados-impactosEsperadoProyecto">Impactos Esperado Proyecto</label>
                        <select class="form-control" id="impactos-esperados-impactosEsperadoProyecto" name="impactosEsperadoProyecto" v-model="impactosEsperados.impactosEsperadoProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.impactosEsperados.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./impactos-esperados-update.component.ts">
</script>

// src/main/webapp/app/entities/impactos-esperados/impactos-esperados-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IImpactosEsperados, ImpactosEsperados } from 'app/shared/model/impactos-esperados.model';
import { ImpactosEsperadosService } from './impactos-esperados.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';

@Component({
  selector: 'jhi-impactos-esperados-update',
  templateUrl: './impactos-esperados-update.component.html'
})
export class ImpactosEsperadosUpdateComponent implements OnInit {
  impactosEsperados: IImpactosEsperados;
  isSaving: boolean;

  proyectos: IProyecto[];

  editForm = this.fb.group({
    id: [],
    impacto: [],
    plazo: [],
    indicador: [],
    supuestos: [],
    proyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected impactosEsperadosService: ImpactosEsperadosService,
    protected proyectoService: ProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ impactosEsperados }) => {
      this.updateForm(impactosEsperados);
      this.impactosEsperados = impactosEsperados;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(impactosEsperados: IImpactosEsperados) {
    this.editForm.patchValue({
      id: impactosEsperados.id,
      impacto: impactosEsperados.impacto,
      plazo: impactosEsperados.plazo,
      indicador: impactosEsperados.indicador,
      supuestos: impactosEsperados.supuestos,
      proyecto: impactosEsperados.proyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const impactosEsperados = this.createFromForm();
    if (impactosEsperados.id !== undefined) {
      this.subscribeToSaveResponse(this.impactosEsperadosService.update(impactosEsperados));
    } else {
      this.subscribeToSaveResponse(this.impactosEsperadosService.create(impactosEsperados));
    }
  }

  private createFromForm(): IImpactosEsperados {
    const entity = {
      ...new ImpactosEsperados(),
      id: this.editForm.get(['id']).value,
      impacto: this.editForm.get(['impacto']).value,
      plazo: this.editForm.get(['plazo']).value,
      indicador: this.editForm.get(['indicador']).value,
      supuestos: this.editForm.get(['supuestos']).value,
      proyecto: this.editForm.get(['proyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IImpactosEsperados>>) {
    result.subscribe((res: HttpResponse<IImpactosEsperados>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-impactos-esperados-heading" jhiTranslate="ciecytApp.impactosEsperados.home.createOrEditLabel">Create or edit a Impactos Esperados</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!impactosEsperados.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.impactosEsperados.impacto" for="field_impacto">Impacto</label>
                    <input type="text" class="form-control" name="impacto" id="field_impacto"
                           formControlName="impacto"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.impactosEsperados.plazo" for="field_plazo">Plazo</label>
                    <input type="number" class="form-control" name="plazo" id="field_plazo"
                           formControlName="plazo"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.impactosEsperados.indicador" for="field_indicador">Indicador</label>
                    <input type="text" class="form-control" name="indicador" id="field_indicador"
                           formControlName="indicador"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.impactosEsperados.supuestos" for="field_supuestos">Supuestos</label>
                    <input type="text" class="form-control" name="supuestos" id="field_supuestos"
                           formControlName="supuestos"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.impactosEsperados.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
