// src/main/webapp/app/entities/solicitud/solicitud.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { ISolicitud } from 'app/shared/model/solicitud.model';
import { AccountService } from 'app/core';
import { SolicitudService } from './solicitud.service';

@Component({
  selector: 'jhi-solicitud',
  templateUrl: './solicitud.component.html'
})
export class SolicitudComponent implements OnInit, OnDestroy {
  solicituds: ISolicitud[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected solicitudService: SolicitudService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.solicitudService
      .query()
      .pipe(
        filter((res: HttpResponse<ISolicitud[]>) => res.ok),
        map((res: HttpResponse<ISolicitud[]>) => res.body)
      )
      .subscribe(
        (res: ISolicitud[]) => {
          this.solicituds = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInSolicituds();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: ISolicitud) {
    return item.id;
  }

  registerChangeInSolicituds() {
    this.eventSubscriber = this.eventManager.subscribe('solicitudListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.solicitud.home.title">Solicituds</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-solicitud" [routerLink]="['/solicitud/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.solicitud.home.createLabel">
            Create new Solicitud
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="solicituds">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.solicitud.estado">Estado</span></th>
            <th><span jhiTranslate="ciecytApp.solicitud.asunto">Asunto</span></th>
            <th><span jhiTranslate="ciecytApp.solicitud.fechaCreancion">Fecha Creancion</span></th>
            <th><span jhiTranslate="ciecytApp.solicitud.integrantesProyecto">Integrantes Proyecto</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let solicitud of solicituds ;trackBy: trackId">
                <td><a [routerLink]="['/solicitud', solicitud.id, 'view' ]">{{solicitud.id}}</a></td>
                <td>{{solicitud.estado}}</td>
                <td>{{solicitud.asunto}}</td>
                <td>{{solicitud.fechaCreancion | date:'mediumDate'}}</td>
                <td>
                    <div *ngIf="solicitud.integrantesProyecto">
                        <a [routerLink]="['../integrantes-proyecto', solicitud.integrantesProyecto?.id, 'view' ]" >{{solicitud.integrantesProyecto?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/solicitud', solicitud.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/solicitud', solicitud.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'solicitud', { outlets: { popup: solicitud.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>

// src/main/webapp/app/entities/solicitud/solicitud.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.solicitud.home.title')" id="solicitud-heading">Solicituds</span>
            <router-link :to="{name: 'SolicitudCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-solicitud">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.solicitud.home.createLabel')">
                    Create a new Solicitud
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && solicituds && solicituds.length === 0">
            <span v-text="$t('ciecytApp.solicitud.home.notFound')">No solicituds found</span>
        </div>
        <div class="table-responsive" v-if="solicituds && solicituds.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('estado')"><span v-text="$t('ciecytApp.solicitud.estado')">Estado</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('asunto')"><span v-text="$t('ciecytApp.solicitud.asunto')">Asunto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('textoSolicitud')"><span v-text="$t('ciecytApp.solicitud.textoSolicitud')">Texto Solicitud</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fechaSolicitud')"><span v-text="$t('ciecytApp.solicitud.fechaSolicitud')">Fecha Solicitud</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('solicitudIntegranteProyectoIntegrante')"><span v-text="$t('ciecytApp.solicitud.solicitudIntegranteProyecto')">Solicitud Integrante Proyecto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="solicitud in solicituds"
                    :key="solicitud.id">
                    <td>
                        <router-link :to="{name: 'SolicitudView', params: {solicitudId: solicitud.id}}">{{solicitud.id}}</router-link>
                    </td>
                    <td>{{solicitud.estado}}</td>
                    <td>{{solicitud.asunto}}</td>
                    <td>{{solicitud.textoSolicitud}}</td>
                    <td>{{solicitud.fechaSolicitud}}</td>
                    <td>
                        <div v-if="solicitud.solicitudIntegranteProyectoId">
                            <router-link :to="{name: 'IntegranteProyectoView', params: {solicitudIntegranteProyectoId: solicitud.solicitudIntegranteProyectoId}}">{{solicitud.solicitudIntegranteProyectoIntegrante}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'SolicitudView', params: {solicitudId: solicitud.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'SolicitudEdit', params: {solicitudId: solicitud.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(solicitud)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.solicitud.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-solicitud-heading" v-bind:title="$t('ciecytApp.solicitud.delete.question')">Are you sure you want to delete this Solicitud?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-solicitud" v-text="$t('entity.action.delete')" v-on:click="removeSolicitud()">Delete</button>
            </div>
        </b-modal>
        <div v-show="solicituds && solicituds.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./solicitud.component.ts">
</script>
