// src/main/webapp/app/entities/solicitud/solicitud-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { ISolicitud, Solicitud } from 'app/shared/model/solicitud.model';
import { SolicitudService } from './solicitud.service';
import { IIntegrantesProyecto } from 'app/shared/model/integrantes-proyecto.model';
import { IntegrantesProyectoService } from 'app/entities/integrantes-proyecto';

@Component({
  selector: 'jhi-solicitud-update',
  templateUrl: './solicitud-update.component.html'
})
export class SolicitudUpdateComponent implements OnInit {
  solicitud: ISolicitud;
  isSaving: boolean;

  integrantesproyectos: IIntegrantesProyecto[];
  fechaCreancionDp: any;

  editForm = this.fb.group({
    id: [],
    estado: [],
    asunto: [],
    fechaCreancion: [],
    integrantesProyecto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected solicitudService: SolicitudService,
    protected integrantesProyectoService: IntegrantesProyectoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ solicitud }) => {
      this.updateForm(solicitud);
      this.solicitud = solicitud;
    });
    this.integrantesProyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IIntegrantesProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IIntegrantesProyecto[]>) => response.body)
      )
      .subscribe((res: IIntegrantesProyecto[]) => (this.integrantesproyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(solicitud: ISolicitud) {
    this.editForm.patchValue({
      id: solicitud.id,
      estado: solicitud.estado,
      asunto: solicitud.asunto,
      fechaCreancion: solicitud.fechaCreancion,
      integrantesProyecto: solicitud.integrantesProyecto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const solicitud = this.createFromForm();
    if (solicitud.id !== undefined) {
      this.subscribeToSaveResponse(this.solicitudService.update(solicitud));
    } else {
      this.subscribeToSaveResponse(this.solicitudService.create(solicitud));
    }
  }

  private createFromForm(): ISolicitud {
    const entity = {
      ...new Solicitud(),
      id: this.editForm.get(['id']).value,
      estado: this.editForm.get(['estado']).value,
      asunto: this.editForm.get(['asunto']).value,
      fechaCreancion: this.editForm.get(['fechaCreancion']).value,
      integrantesProyecto: this.editForm.get(['integrantesProyecto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISolicitud>>) {
    result.subscribe((res: HttpResponse<ISolicitud>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackIntegrantesProyectoById(index: number, item: IIntegrantesProyecto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-solicitud-heading" jhiTranslate="ciecytApp.solicitud.home.createOrEditLabel">Create or edit a Solicitud</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!solicitud.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.solicitud.estado" for="field_estado">Estado</label>
                    <input type="checkbox" class="form-control" name="estado" id="field_estado"
                           formControlName="estado"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.solicitud.asunto" for="field_asunto">Asunto</label>
                    <input type="text" class="form-control" name="asunto" id="field_asunto"
                           formControlName="asunto"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.solicitud.fechaCreancion" for="field_fechaCreancion">Fecha Creancion</label>
                    <div class="input-group">
                        <input id="field_fechaCreancion" type="text" class="form-control" name="fechaCreancion" ngbDatepicker  #fechaCreancionDp="ngbDatepicker" formControlName="fechaCreancion"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="fechaCreancionDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.solicitud.integrantesProyecto" for="field_integrantesProyecto">Integrantes Proyecto</label>
                    <select class="form-control" id="field_integrantesProyecto" name="integrantesProyecto" formControlName="integrantesProyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="integrantesProyectoOption.id === editForm.get('integrantesProyecto').value?.id ? editForm.get('integrantesProyecto').value : integrantesProyectoOption" *ngFor="let integrantesProyectoOption of integrantesproyectos; trackBy: trackIntegrantesProyectoById">{{integrantesProyectoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/solicitud/solicitud-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.solicitud.home.createOrEditLabel" v-text="$t('ciecytApp.solicitud.home.createOrEditLabel')">Create or edit a Solicitud</h2>
                <div>
                    <div class="mb-3 form-group" v-if="solicitud.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="solicitud.id" readonly />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.solicitud.estado')" for="solicitud-estado">Estado</label>
                        <input type="checkbox" class="form-check" name="estado" id="solicitud-estado"
                            :class="{'valid': !$v.solicitud.estado.$invalid, 'invalid': $v.solicitud.estado.$invalid }" v-model="$v.solicitud.estado.$model" />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.solicitud.asunto')" for="solicitud-asunto">Asunto</label>
                        <input type="text" class="form-control" name="asunto" id="solicitud-asunto"
                            :class="{'valid': !$v.solicitud.asunto.$invalid, 'invalid': $v.solicitud.asunto.$invalid }" v-model="$v.solicitud.asunto.$model" />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.solicitud.textoSolicitud')" for="solicitud-textoSolicitud">Texto Solicitud</label>
                        <input type="text" class="form-control" name="textoSolicitud" id="solicitud-textoSolicitud"
                            :class="{'valid': !$v.solicitud.textoSolicitud.$invalid, 'invalid': $v.solicitud.textoSolicitud.$invalid }" v-model="$v.solicitud.textoSolicitud.$model" />
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.solicitud.fechaSolicitud')" for="solicitud-fechaSolicitud">Fecha Solicitud</label>
                        <div class="input-group">
                            <input id="solicitud-fechaSolicitud" type="date" class="form-control" name="fechaSolicitud"  :class="{'valid': !$v.solicitud.fechaSolicitud.$invalid, 'invalid': $v.solicitud.fechaSolicitud.$invalid }"
                            v-model="$v.solicitud.fechaSolicitud.$model"  />
                        </div>
                    </div>
                    <div class="mb-3 form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.solicitud.solicitudIntegranteProyecto')" for="solicitud-solicitudIntegranteProyecto">Solicitud Integrante Proyecto</label>
                        <select class="form-control" id="solicitud-solicitudIntegranteProyecto" name="solicitudIntegranteProyecto" v-model="solicitud.solicitudIntegranteProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="integranteProyectoOption.id" v-for="integranteProyectoOption in integranteProyectos" :key="integranteProyectoOption.id">{{integranteProyectoOption.integrante}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.solicitud.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./solicitud-update.component.ts">
</script>
