// src/main/webapp/app/entities/producto-proyecto/producto-proyecto-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.productoProyecto.home.createOrEditLabel" v-text="$t('ciecytApp.productoProyecto.home.createOrEditLabel')">Create or edit a ProductoProyecto</h2>
                <div>
                    <div class="form-group" v-if="productoProyecto.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="productoProyecto.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.productoProyecto.aplica')" for="producto-proyecto-aplica">Aplica</label>
                        <input type="checkbox" class="form-check" name="aplica" id="producto-proyecto-aplica"
                            :class="{'valid': !$v.productoProyecto.aplica.$invalid, 'invalid': $v.productoProyecto.aplica.$invalid }" v-model="$v.productoProyecto.aplica.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.productoProyecto.descripcion')" for="producto-proyecto-descripcion">Descripcion</label>
                        <input type="text" class="form-control" name="descripcion" id="producto-proyecto-descripcion"
                            :class="{'valid': !$v.productoProyecto.descripcion.$invalid, 'invalid': $v.productoProyecto.descripcion.$invalid }" v-model="$v.productoProyecto.descripcion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.productoProyecto.productoProyectoProducto')" for="producto-proyecto-productoProyectoProducto">Producto Proyecto Producto</label>
                        <select class="form-control" id="producto-proyecto-productoProyectoProducto" name="productoProyectoProducto" v-model="productoProyecto.productoProyectoProductoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="productoOption.id" v-for="productoOption in productos" :key="productoOption.id">{{productoOption.producto}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.productoProyecto.productoProyectoProyecto')" for="producto-proyecto-productoProyectoProyecto">Producto Proyecto Proyecto</label>
                        <select class="form-control" id="producto-proyecto-productoProyectoProyecto" name="productoProyectoProyecto" v-model="productoProyecto.productoProyectoProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.productoProyecto.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./producto-proyecto-update.component.ts">
</script>

// src/main/webapp/app/entities/producto-proyecto/producto-proyecto-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IProductoProyecto, ProductoProyecto } from 'app/shared/model/producto-proyecto.model';
import { ProductoProyectoService } from './producto-proyecto.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';
import { IProducto } from 'app/shared/model/producto.model';
import { ProductoService } from 'app/entities/producto';

@Component({
  selector: 'jhi-producto-proyecto-update',
  templateUrl: './producto-proyecto-update.component.html'
})
export class ProductoProyectoUpdateComponent implements OnInit {
  productoProyecto: IProductoProyecto;
  isSaving: boolean;

  proyectos: IProyecto[];

  productos: IProducto[];

  editForm = this.fb.group({
    id: [],
    aplica: [],
    descripcion: [],
    proyecto: [],
    producto: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected productoProyectoService: ProductoProyectoService,
    protected proyectoService: ProyectoService,
    protected productoService: ProductoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ productoProyecto }) => {
      this.updateForm(productoProyecto);
      this.productoProyecto = productoProyecto;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.productoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProducto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProducto[]>) => response.body)
      )
      .subscribe((res: IProducto[]) => (this.productos = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(productoProyecto: IProductoProyecto) {
    this.editForm.patchValue({
      id: productoProyecto.id,
      aplica: productoProyecto.aplica,
      descripcion: productoProyecto.descripcion,
      proyecto: productoProyecto.proyecto,
      producto: productoProyecto.producto
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const productoProyecto = this.createFromForm();
    if (productoProyecto.id !== undefined) {
      this.subscribeToSaveResponse(this.productoProyectoService.update(productoProyecto));
    } else {
      this.subscribeToSaveResponse(this.productoProyectoService.create(productoProyecto));
    }
  }

  private createFromForm(): IProductoProyecto {
    const entity = {
      ...new ProductoProyecto(),
      id: this.editForm.get(['id']).value,
      aplica: this.editForm.get(['aplica']).value,
      descripcion: this.editForm.get(['descripcion']).value,
      proyecto: this.editForm.get(['proyecto']).value,
      producto: this.editForm.get(['producto']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProductoProyecto>>) {
    result.subscribe((res: HttpResponse<IProductoProyecto>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }

  trackProductoById(index: number, item: IProducto) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-producto-proyecto-heading" jhiTranslate="ciecytApp.productoProyecto.home.createOrEditLabel">Create or edit a Producto Proyecto</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!productoProyecto.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.productoProyecto.aplica" for="field_aplica">Aplica</label>
                    <input type="checkbox" class="form-control" name="aplica" id="field_aplica"
                           formControlName="aplica"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.productoProyecto.descripcion" for="field_descripcion">Descripcion</label>
                    <input type="text" class="form-control" name="descripcion" id="field_descripcion"
                           formControlName="descripcion"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.productoProyecto.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.productoProyecto.producto" for="field_producto">Producto</label>
                    <select class="form-control" id="field_producto" name="producto" formControlName="producto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="productoOption.id === editForm.get('producto').value?.id ? editForm.get('producto').value : productoOption" *ngFor="let productoOption of productos; trackBy: trackProductoById">{{productoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
