// src/main/webapp/app/entities/producto-proyecto/producto-proyecto.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.productoProyecto.home.title')" id="producto-proyecto-heading">Producto Proyectos</span>
            <router-link :to="{name: 'ProductoProyectoCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-producto-proyecto">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.productoProyecto.home.createLabel')">
                    Create a new Producto Proyecto
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && productoProyectos && productoProyectos.length === 0">
            <span v-text="$t('ciecytApp.productoProyecto.home.notFound')">No productoProyectos found</span>
        </div>
        <div class="table-responsive" v-if="productoProyectos && productoProyectos.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('aplica')"><span v-text="$t('ciecytApp.productoProyecto.aplica')">Aplica</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('descripcion')"><span v-text="$t('ciecytApp.productoProyecto.descripcion')">Descripcion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('productoProyectoProductoProducto')"><span v-text="$t('ciecytApp.productoProyecto.productoProyectoProducto')">Producto Proyecto Producto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('productoProyectoProyectoTitulo')"><span v-text="$t('ciecytApp.productoProyecto.productoProyectoProyecto')">Producto Proyecto Proyecto</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="productoProyecto in productoProyectos"
                    :key="productoProyecto.id">
                    <td>
                        <router-link :to="{name: 'ProductoProyectoView', params: {productoProyectoId: productoProyecto.id}}">{{productoProyecto.id}}</router-link>
                    </td>
                    <td>{{productoProyecto.aplica}}</td>
                    <td>{{productoProyecto.descripcion}}</td>
                    <td>
                        <div v-if="productoProyecto.productoProyectoProductoId">
                            <router-link :to="{name: 'ProductoView', params: {productoProyectoProductoId: productoProyecto.productoProyectoProductoId}}">{{productoProyecto.productoProyectoProductoProducto}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="productoProyecto.productoProyectoProyectoId">
                            <router-link :to="{name: 'ProyectoView', params: {productoProyectoProyectoId: productoProyecto.productoProyectoProyectoId}}">{{productoProyecto.productoProyectoProyectoTitulo}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'ProductoProyectoView', params: {productoProyectoId: productoProyecto.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'ProductoProyectoEdit', params: {productoProyectoId: productoProyecto.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(productoProyecto)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.productoProyecto.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-productoProyecto-heading" v-bind:title="$t('ciecytApp.productoProyecto.delete.question')">Are you sure you want to delete this Producto Proyecto?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-productoProyecto" v-text="$t('entity.action.delete')" v-on:click="removeProductoProyecto()">Delete</button>
            </div>
        </b-modal>
        <div v-show="productoProyectos && productoProyectos.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./producto-proyecto.component.ts">
</script>

// src/main/webapp/app/entities/producto-proyecto/producto-proyecto.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpResponse } from '@angular/common/http';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiAlertService } from 'ng-jhipster';

import { IProductoProyecto } from 'app/shared/model/producto-proyecto.model';
import { AccountService } from 'app/core';
import { ProductoProyectoService } from './producto-proyecto.service';

@Component({
  selector: 'jhi-producto-proyecto',
  templateUrl: './producto-proyecto.component.html'
})
export class ProductoProyectoComponent implements OnInit, OnDestroy {
  productoProyectos: IProductoProyecto[];
  currentAccount: any;
  eventSubscriber: Subscription;

  constructor(
    protected productoProyectoService: ProductoProyectoService,
    protected jhiAlertService: JhiAlertService,
    protected eventManager: JhiEventManager,
    protected accountService: AccountService
  ) {}

  loadAll() {
    this.productoProyectoService
      .query()
      .pipe(
        filter((res: HttpResponse<IProductoProyecto[]>) => res.ok),
        map((res: HttpResponse<IProductoProyecto[]>) => res.body)
      )
      .subscribe(
        (res: IProductoProyecto[]) => {
          this.productoProyectos = res;
        },
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInProductoProyectos();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IProductoProyecto) {
    return item.id;
  }

  registerChangeInProductoProyectos() {
    this.eventSubscriber = this.eventManager.subscribe('productoProyectoListModification', response => this.loadAll());
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.productoProyecto.home.title">Producto Proyectos</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-producto-proyecto" [routerLink]="['/producto-proyecto/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.productoProyecto.home.createLabel">
            Create new Producto Proyecto
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="productoProyectos">
        <table class="table table-striped">
            <thead>
            <tr>
            <th><span jhiTranslate="global.field.id">ID</span></th>
            <th><span jhiTranslate="ciecytApp.productoProyecto.aplica">Aplica</span></th>
            <th><span jhiTranslate="ciecytApp.productoProyecto.descripcion">Descripcion</span></th>
            <th><span jhiTranslate="ciecytApp.productoProyecto.proyecto">Proyecto</span></th>
            <th><span jhiTranslate="ciecytApp.productoProyecto.producto">Producto</span></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let productoProyecto of productoProyectos ;trackBy: trackId">
                <td><a [routerLink]="['/producto-proyecto', productoProyecto.id, 'view' ]">{{productoProyecto.id}}</a></td>
                <td>{{productoProyecto.aplica}}</td>
                <td>{{productoProyecto.descripcion}}</td>
                <td>
                    <div *ngIf="productoProyecto.proyecto">
                        <a [routerLink]="['../proyecto', productoProyecto.proyecto?.id, 'view' ]" >{{productoProyecto.proyecto?.id}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="productoProyecto.producto">
                        <a [routerLink]="['../producto', productoProyecto.producto?.id, 'view' ]" >{{productoProyecto.producto?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/producto-proyecto', productoProyecto.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/producto-proyecto', productoProyecto.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'producto-proyecto', { outlets: { popup: productoProyecto.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
