// src/main/webapp/app/entities/proyecto/proyecto.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpErrorResponse, HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiEventManager, JhiParseLinks, JhiAlertService } from 'ng-jhipster';

import { IProyecto } from 'app/shared/model/proyecto.model';
import { AccountService } from 'app/core';

import { ITEMS_PER_PAGE } from 'app/shared';
import { ProyectoService } from './proyecto.service';

@Component({
  selector: 'jhi-proyecto',
  templateUrl: './proyecto.component.html'
})
export class ProyectoComponent implements OnInit, OnDestroy {
  currentAccount: any;
  proyectos: IProyecto[];
  error: any;
  success: any;
  eventSubscriber: Subscription;
  routeData: any;
  links: any;
  totalItems: any;
  itemsPerPage: any;
  page: any;
  predicate: any;
  previousPage: any;
  reverse: any;

  constructor(
    protected proyectoService: ProyectoService,
    protected parseLinks: JhiParseLinks,
    protected jhiAlertService: JhiAlertService,
    protected accountService: AccountService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager
  ) {
    this.itemsPerPage = ITEMS_PER_PAGE;
    this.routeData = this.activatedRoute.data.subscribe(data => {
      this.page = data.pagingParams.page;
      this.previousPage = data.pagingParams.page;
      this.reverse = data.pagingParams.ascending;
      this.predicate = data.pagingParams.predicate;
    });
  }

  loadAll() {
    this.proyectoService
      .query({
        page: this.page - 1,
        size: this.itemsPerPage,
        sort: this.sort()
      })
      .subscribe(
        (res: HttpResponse<IProyecto[]>) => this.paginateProyectos(res.body, res.headers),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
  }

  loadPage(page: number) {
    if (page !== this.previousPage) {
      this.previousPage = page;
      this.transition();
    }
  }

  transition() {
    this.router.navigate(['/proyecto'], {
      queryParams: {
        page: this.page,
        size: this.itemsPerPage,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    });
    this.loadAll();
  }

  clear() {
    this.page = 0;
    this.router.navigate([
      '/proyecto',
      {
        page: this.page,
        sort: this.predicate + ',' + (this.reverse ? 'asc' : 'desc')
      }
    ]);
    this.loadAll();
  }

  ngOnInit() {
    this.loadAll();
    this.accountService.identity().then(account => {
      this.currentAccount = account;
    });
    this.registerChangeInProyectos();
  }

  ngOnDestroy() {
    this.eventManager.destroy(this.eventSubscriber);
  }

  trackId(index: number, item: IProyecto) {
    return item.id;
  }

  registerChangeInProyectos() {
    this.eventSubscriber = this.eventManager.subscribe('proyectoListModification', response => this.loadAll());
  }

  sort() {
    const result = [this.predicate + ',' + (this.reverse ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected paginateProyectos(data: IProyecto[], headers: HttpHeaders) {
    this.links = this.parseLinks.parse(headers.get('link'));
    this.totalItems = parseInt(headers.get('X-Total-Count'), 10);
    this.proyectos = data;
  }

  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="ciecytApp.proyecto.home.title">Proyectos</span>
        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-proyecto" [routerLink]="['/proyecto/new']">
            <fa-icon [icon]="'plus'"></fa-icon>
            <span  jhiTranslate="ciecytApp.proyecto.home.createLabel">
            Create new Proyecto
            </span>
        </button>
    </h2>
    <jhi-alert></jhi-alert>
    <br/>
    <div class="table-responsive" *ngIf="proyectos">
        <table class="table table-striped">
            <thead>
            <tr jhiSort [(predicate)]="predicate" [(ascending)]="reverse" [callback]="transition.bind(this)">
            <th jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="titulo"><span jhiTranslate="ciecytApp.proyecto.titulo">Titulo</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="url"><span jhiTranslate="ciecytApp.proyecto.url">Url</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="lugarEjecucion"><span jhiTranslate="ciecytApp.proyecto.lugarEjecucion">Lugar Ejecucion</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="duracion"><span jhiTranslate="ciecytApp.proyecto.duracion">Duracion</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="fechaIni"><span jhiTranslate="ciecytApp.proyecto.fechaIni">Fecha Ini</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="fechaFin"><span jhiTranslate="ciecytApp.proyecto.fechaFin">Fecha Fin</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="contrapartidaPesos"><span jhiTranslate="ciecytApp.proyecto.contrapartidaPesos">Contrapartida Pesos</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="contrapartidaEspecie"><span jhiTranslate="ciecytApp.proyecto.contrapartidaEspecie">Contrapartida Especie</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="palabraClave"><span jhiTranslate="ciecytApp.proyecto.palabraClave">Palabra Clave</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="convocatoria"><span jhiTranslate="ciecytApp.proyecto.convocatoria">Convocatoria</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="lineaDeInvestigacion.id"><span jhiTranslate="ciecytApp.proyecto.lineaDeInvestigacion">Linea De Investigacion</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="grupoSemillero.id"><span jhiTranslate="ciecytApp.proyecto.grupoSemillero">Grupo Semillero</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="facultad.id"><span jhiTranslate="ciecytApp.proyecto.facultad">Facultad</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th jhiSortBy="modalidadDeGrado.id"><span jhiTranslate="ciecytApp.proyecto.modalidadDeGrado">Modalidad De Grado</span> <fa-icon [icon]="'sort'"></fa-icon></th>
            <th></th>
            </tr>
            </thead>
            <tbody>
            <tr *ngFor="let proyecto of proyectos ;trackBy: trackId">
                <td><a [routerLink]="['/proyecto', proyecto.id, 'view' ]">{{proyecto.id}}</a></td>
                <td>{{proyecto.titulo}}</td>
                <td>{{proyecto.url}}</td>
                <td>{{proyecto.lugarEjecucion}}</td>
                <td>{{proyecto.duracion}}</td>
                <td>{{proyecto.fechaIni | date:'mediumDate'}}</td>
                <td>{{proyecto.fechaFin | date:'mediumDate'}}</td>
                <td>{{proyecto.contrapartidaPesos}}</td>
                <td>{{proyecto.contrapartidaEspecie}}</td>
                <td>{{proyecto.palabraClave}}</td>
                <td>{{proyecto.convocatoria}}</td>
                <td>
                    <div *ngIf="proyecto.lineaDeInvestigacion">
                        <a [routerLink]="['../linea-de-investigacion', proyecto.lineaDeInvestigacion?.id, 'view' ]" >{{proyecto.lineaDeInvestigacion?.id}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="proyecto.grupoSemillero">
                        <a [routerLink]="['../grupo-semillero', proyecto.grupoSemillero?.id, 'view' ]" >{{proyecto.grupoSemillero?.id}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="proyecto.facultad">
                        <a [routerLink]="['../facultad', proyecto.facultad?.id, 'view' ]" >{{proyecto.facultad?.id}}</a>
                    </div>
                </td>
                <td>
                    <div *ngIf="proyecto.modalidadDeGrado">
                        <a [routerLink]="['../modalidad-de-grado', proyecto.modalidadDeGrado?.id, 'view' ]" >{{proyecto.modalidadDeGrado?.id}}</a>
                    </div>
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="submit"
                                [routerLink]="['/proyecto', proyecto.id, 'view' ]"
                                class="btn btn-info btn-sm">
                            <fa-icon [icon]="'eye'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/proyecto', proyecto.id, 'edit']"
                                class="btn btn-primary btn-sm">
                            <fa-icon [icon]="'pencil-alt'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                        </button>
                        <button type="submit"
                                [routerLink]="['/', 'proyecto', { outlets: { popup: proyecto.id + '/delete'} }]"
                                replaceUrl="true"
                                queryParamsHandling="merge"
                                class="btn btn-danger btn-sm">
                            <fa-icon [icon]="'times'"></fa-icon>
                            <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                        </button>
                    </div>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div *ngIf="proyectos && proyectos.length">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [maxSize]="5" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>
        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="page" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage(page)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/proyecto/proyecto.vue
<template>
    <div>
        <h2 id="page-heading">
            <span v-text="$t('ciecytApp.proyecto.home.title')" id="proyecto-heading">Proyectos</span>
            <router-link :to="{name: 'ProyectoCreate'}" tag="button" id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-proyecto">
                <font-awesome-icon icon="plus"></font-awesome-icon>
                <span  v-text="$t('ciecytApp.proyecto.home.createLabel')">
                    Create a new Proyecto
                </span>
            </router-link>
        </h2>
        <b-alert :show="dismissCountDown"
            dismissible
            :variant="alertType"
            @dismissed="dismissCountDown=0"
            @dismiss-count-down="countDownChanged">
            {{alertMessage}}
        </b-alert>
        <br/>
        <div class="alert alert-warning" v-if="!isFetching && proyectos && proyectos.length === 0">
            <span v-text="$t('ciecytApp.proyecto.home.notFound')">No proyectos found</span>
        </div>
        <div class="table-responsive" v-if="proyectos && proyectos.length > 0">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th v-on:click="changeOrder('id')"><span v-text="$t('global.field.id')">ID</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('titulo')"><span v-text="$t('ciecytApp.proyecto.titulo')">Titulo</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('url')"><span v-text="$t('ciecytApp.proyecto.url')">Url</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('lugarEjecucion')"><span v-text="$t('ciecytApp.proyecto.lugarEjecucion')">Lugar Ejecucion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('duracion')"><span v-text="$t('ciecytApp.proyecto.duracion')">Duracion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fechaIni')"><span v-text="$t('ciecytApp.proyecto.fechaIni')">Fecha Ini</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('fechaFin')"><span v-text="$t('ciecytApp.proyecto.fechaFin')">Fecha Fin</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('contrapartidaPesos')"><span v-text="$t('ciecytApp.proyecto.contrapartidaPesos')">Contrapartida Pesos</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('contrapartidaEspecie')"><span v-text="$t('ciecytApp.proyecto.contrapartidaEspecie')">Contrapartida Especie</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('palabrasClave')"><span v-text="$t('ciecytApp.proyecto.palabrasClave')">Palabras Clave</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('convocatoria')"><span v-text="$t('ciecytApp.proyecto.convocatoria')">Convocatoria</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('proyectoLineaInvestigacionLinea')"><span v-text="$t('ciecytApp.proyecto.proyectoLineaInvestigacion')">Proyecto Linea Investigacion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('proyectoGrupoSemilleroNombre')"><span v-text="$t('ciecytApp.proyecto.proyectoGrupoSemillero')">Proyecto Grupo Semillero</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('proyectoModalidadModalidad')"><span v-text="$t('ciecytApp.proyecto.proyectoModalidad')">Proyecto Modalidad</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('facultadId')"><span v-text="$t('ciecytApp.proyecto.facultad')">Facultad</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th v-on:click="changeOrder('subLineaLineaInvestigacionLinea')"><span v-text="$t('ciecytApp.proyecto.subLineaLineaInvestigacion')">Sub Linea Linea Investigacion</span> <font-awesome-icon icon="sort"></font-awesome-icon></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr v-for="proyecto in proyectos"
                    :key="proyecto.id">
                    <td>
                        <router-link :to="{name: 'ProyectoView', params: {proyectoId: proyecto.id}}">{{proyecto.id}}</router-link>
                    </td>
                    <td>{{proyecto.titulo}}</td>
                    <td>{{proyecto.url}}</td>
                    <td>{{proyecto.lugarEjecucion}}</td>
                    <td>{{proyecto.duracion}}</td>
                    <td>{{proyecto.fechaIni}}</td>
                    <td>{{proyecto.fechaFin}}</td>
                    <td>{{proyecto.contrapartidaPesos}}</td>
                    <td>{{proyecto.contrapartidaEspecie}}</td>
                    <td>{{proyecto.palabrasClave}}</td>
                    <td>{{proyecto.convocatoria}}</td>
                    <td>
                        <div v-if="proyecto.proyectoLineaInvestigacionId">
                            <router-link :to="{name: 'LineaInvestigacionView', params: {proyectoLineaInvestigacionId: proyecto.proyectoLineaInvestigacionId}}">{{proyecto.proyectoLineaInvestigacionLinea}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="proyecto.proyectoGrupoSemilleroId">
                            <router-link :to="{name: 'GrupoSemilleroView', params: {proyectoGrupoSemilleroId: proyecto.proyectoGrupoSemilleroId}}">{{proyecto.proyectoGrupoSemilleroNombre}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="proyecto.proyectoModalidadId">
                            <router-link :to="{name: 'ModalidadView', params: {proyectoModalidadId: proyecto.proyectoModalidadId}}">{{proyecto.proyectoModalidadModalidad}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="proyecto.facultadId">
                            <router-link :to="{name: 'FacultadView', params: {facultadId: proyecto.facultadId}}">{{proyecto.facultadId}}</router-link>
                        </div>
                    </td>
                    <td>
                        <div v-if="proyecto.subLineaLineaInvestigacionId">
                            <router-link :to="{name: 'LineaInvestigacionView', params: {subLineaLineaInvestigacionId: proyecto.subLineaLineaInvestigacionId}}">{{proyecto.subLineaLineaInvestigacionLinea}}</router-link>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <router-link :to="{name: 'ProyectoView', params: {proyectoId: proyecto.id}}" tag="button" class="btn btn-info btn-sm details">
                                <font-awesome-icon icon="eye"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.view')">View</span>
                            </router-link>
                            <router-link :to="{name: 'ProyectoEdit', params: {proyectoId: proyecto.id}}"  tag="button" class="btn btn-primary btn-sm edit">
                                <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.edit')">Edit</span>
                            </router-link>
                            <b-button v-on:click="prepareRemove(proyecto)"
                                   variant="danger"
                                   class="btn btn-sm"
                                   v-b-modal.removeEntity>
                                <font-awesome-icon icon="times"></font-awesome-icon>
                                <span class="d-none d-md-inline" v-text="$t('entity.action.delete')">Delete</span>
                            </b-button>
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <b-modal ref="removeEntity" id="removeEntity" >
            <span slot="modal-title"><span id="ciecytApp.proyecto.delete.question" v-text="$t('entity.delete.title')">Confirm delete operation</span></span>
            <div class="modal-body">
                <p id="jhi-delete-proyecto-heading" v-bind:title="$t('ciecytApp.proyecto.delete.question')">Are you sure you want to delete this Proyecto?</p>
            </div>
            <div slot="modal-footer">
                <button type="button" class="btn btn-secondary" v-text="$t('entity.action.cancel')" v-on:click="closeDialog()">Cancel</button>
                <button type="button" class="btn btn-primary" id="jhi-confirm-delete-proyecto" v-text="$t('entity.action.delete')" v-on:click="removeProyecto()">Delete</button>
            </div>
        </b-modal>
        <div v-show="proyectos && proyectos.length > 0">
            <div class="row justify-content-center">
                <jhi-item-count :page="page" :total="queryCount" :itemsPerPage="itemsPerPage"></jhi-item-count>
            </div>
            <div class="row justify-content-center">
                <b-pagination size="md" :total-rows="totalItems" v-model="page" :per-page="itemsPerPage" :change="loadPage(page)"></b-pagination>
            </div>
        </div>
    </div>
</template>

<script lang="ts" src="./proyecto.component.ts">
</script>
