// src/main/webapp/app/entities/proyecto/proyecto-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import * as moment from 'moment';
import { JhiAlertService } from 'ng-jhipster';
import { IProyecto, Proyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from './proyecto.service';
import { ILineaDeInvestigacion } from 'app/shared/model/linea-de-investigacion.model';
import { LineaDeInvestigacionService } from 'app/entities/linea-de-investigacion';
import { IGrupoSemillero } from 'app/shared/model/grupo-semillero.model';
import { GrupoSemilleroService } from 'app/entities/grupo-semillero';
import { IFacultad } from 'app/shared/model/facultad.model';
import { FacultadService } from 'app/entities/facultad';
import { IModalidadDeGrado } from 'app/shared/model/modalidad-de-grado.model';
import { ModalidadDeGradoService } from 'app/entities/modalidad-de-grado';

@Component({
  selector: 'jhi-proyecto-update',
  templateUrl: './proyecto-update.component.html'
})
export class ProyectoUpdateComponent implements OnInit {
  proyecto: IProyecto;
  isSaving: boolean;

  lineadeinvestigacions: ILineaDeInvestigacion[];

  gruposemilleros: IGrupoSemillero[];

  facultads: IFacultad[];

  modalidaddegrados: IModalidadDeGrado[];
  fechaIniDp: any;
  fechaFinDp: any;

  editForm = this.fb.group({
    id: [],
    titulo: [],
    url: [],
    lugarEjecucion: [],
    duracion: [],
    fechaIni: [],
    fechaFin: [],
    contrapartidaPesos: [],
    contrapartidaEspecie: [],
    palabraClave: [],
    convocatoria: [],
    lineaDeInvestigacion: [],
    grupoSemillero: [],
    facultad: [],
    modalidadDeGrado: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected proyectoService: ProyectoService,
    protected lineaDeInvestigacionService: LineaDeInvestigacionService,
    protected grupoSemilleroService: GrupoSemilleroService,
    protected facultadService: FacultadService,
    protected modalidadDeGradoService: ModalidadDeGradoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ proyecto }) => {
      this.updateForm(proyecto);
      this.proyecto = proyecto;
    });
    this.lineaDeInvestigacionService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<ILineaDeInvestigacion[]>) => mayBeOk.ok),
        map((response: HttpResponse<ILineaDeInvestigacion[]>) => response.body)
      )
      .subscribe(
        (res: ILineaDeInvestigacion[]) => (this.lineadeinvestigacions = res),
        (res: HttpErrorResponse) => this.onError(res.message)
      );
    this.grupoSemilleroService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IGrupoSemillero[]>) => mayBeOk.ok),
        map((response: HttpResponse<IGrupoSemillero[]>) => response.body)
      )
      .subscribe((res: IGrupoSemillero[]) => (this.gruposemilleros = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.facultadService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IFacultad[]>) => mayBeOk.ok),
        map((response: HttpResponse<IFacultad[]>) => response.body)
      )
      .subscribe((res: IFacultad[]) => (this.facultads = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.modalidadDeGradoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IModalidadDeGrado[]>) => mayBeOk.ok),
        map((response: HttpResponse<IModalidadDeGrado[]>) => response.body)
      )
      .subscribe((res: IModalidadDeGrado[]) => (this.modalidaddegrados = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(proyecto: IProyecto) {
    this.editForm.patchValue({
      id: proyecto.id,
      titulo: proyecto.titulo,
      url: proyecto.url,
      lugarEjecucion: proyecto.lugarEjecucion,
      duracion: proyecto.duracion,
      fechaIni: proyecto.fechaIni,
      fechaFin: proyecto.fechaFin,
      contrapartidaPesos: proyecto.contrapartidaPesos,
      contrapartidaEspecie: proyecto.contrapartidaEspecie,
      palabraClave: proyecto.palabraClave,
      convocatoria: proyecto.convocatoria,
      lineaDeInvestigacion: proyecto.lineaDeInvestigacion,
      grupoSemillero: proyecto.grupoSemillero,
      facultad: proyecto.facultad,
      modalidadDeGrado: proyecto.modalidadDeGrado
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const proyecto = this.createFromForm();
    if (proyecto.id !== undefined) {
      this.subscribeToSaveResponse(this.proyectoService.update(proyecto));
    } else {
      this.subscribeToSaveResponse(this.proyectoService.create(proyecto));
    }
  }

  private createFromForm(): IProyecto {
    const entity = {
      ...new Proyecto(),
      id: this.editForm.get(['id']).value,
      titulo: this.editForm.get(['titulo']).value,
      url: this.editForm.get(['url']).value,
      lugarEjecucion: this.editForm.get(['lugarEjecucion']).value,
      duracion: this.editForm.get(['duracion']).value,
      fechaIni: this.editForm.get(['fechaIni']).value,
      fechaFin: this.editForm.get(['fechaFin']).value,
      contrapartidaPesos: this.editForm.get(['contrapartidaPesos']).value,
      contrapartidaEspecie: this.editForm.get(['contrapartidaEspecie']).value,
      palabraClave: this.editForm.get(['palabraClave']).value,
      convocatoria: this.editForm.get(['convocatoria']).value,
      lineaDeInvestigacion: this.editForm.get(['lineaDeInvestigacion']).value,
      grupoSemillero: this.editForm.get(['grupoSemillero']).value,
      facultad: this.editForm.get(['facultad']).value,
      modalidadDeGrado: this.editForm.get(['modalidadDeGrado']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProyecto>>) {
    result.subscribe((res: HttpResponse<IProyecto>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackLineaDeInvestigacionById(index: number, item: ILineaDeInvestigacion) {
    return item.id;
  }

  trackGrupoSemilleroById(index: number, item: IGrupoSemillero) {
    return item.id;
  }

  trackFacultadById(index: number, item: IFacultad) {
    return item.id;
  }

  trackModalidadDeGradoById(index: number, item: IModalidadDeGrado) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-proyecto-heading" jhiTranslate="ciecytApp.proyecto.home.createOrEditLabel">Create or edit a Proyecto</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!proyecto.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.titulo" for="field_titulo">Titulo</label>
                    <input type="text" class="form-control" name="titulo" id="field_titulo"
                           formControlName="titulo"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.url" for="field_url">Url</label>
                    <input type="text" class="form-control" name="url" id="field_url"
                           formControlName="url"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.lugarEjecucion" for="field_lugarEjecucion">Lugar Ejecucion</label>
                    <input type="text" class="form-control" name="lugarEjecucion" id="field_lugarEjecucion"
                           formControlName="lugarEjecucion"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.duracion" for="field_duracion">Duracion</label>
                    <input type="text" class="form-control" name="duracion" id="field_duracion"
                           formControlName="duracion"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.fechaIni" for="field_fechaIni">Fecha Ini</label>
                    <div class="input-group">
                        <input id="field_fechaIni" type="text" class="form-control" name="fechaIni" ngbDatepicker  #fechaIniDp="ngbDatepicker" formControlName="fechaIni"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="fechaIniDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.fechaFin" for="field_fechaFin">Fecha Fin</label>
                    <div class="input-group">
                        <input id="field_fechaFin" type="text" class="form-control" name="fechaFin" ngbDatepicker  #fechaFinDp="ngbDatepicker" formControlName="fechaFin"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="fechaFinDp.toggle()"><fa-icon [icon]="'calendar-alt'"></fa-icon></button>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.contrapartidaPesos" for="field_contrapartidaPesos">Contrapartida Pesos</label>
                    <input type="number" class="form-control" name="contrapartidaPesos" id="field_contrapartidaPesos"
                           formControlName="contrapartidaPesos"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.contrapartidaEspecie" for="field_contrapartidaEspecie">Contrapartida Especie</label>
                    <input type="number" class="form-control" name="contrapartidaEspecie" id="field_contrapartidaEspecie"
                           formControlName="contrapartidaEspecie"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.palabraClave" for="field_palabraClave">Palabra Clave</label>
                    <input type="text" class="form-control" name="palabraClave" id="field_palabraClave"
                           formControlName="palabraClave"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.convocatoria" for="field_convocatoria">Convocatoria</label>
                    <input type="text" class="form-control" name="convocatoria" id="field_convocatoria"
                           formControlName="convocatoria"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.lineaDeInvestigacion" for="field_lineaDeInvestigacion">Linea De Investigacion</label>
                    <select class="form-control" id="field_lineaDeInvestigacion" name="lineaDeInvestigacion" formControlName="lineaDeInvestigacion">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="lineaDeInvestigacionOption.id === editForm.get('lineaDeInvestigacion').value?.id ? editForm.get('lineaDeInvestigacion').value : lineaDeInvestigacionOption" *ngFor="let lineaDeInvestigacionOption of lineadeinvestigacions; trackBy: trackLineaDeInvestigacionById">{{lineaDeInvestigacionOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.grupoSemillero" for="field_grupoSemillero">Grupo Semillero</label>
                    <select class="form-control" id="field_grupoSemillero" name="grupoSemillero" formControlName="grupoSemillero">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="grupoSemilleroOption.id === editForm.get('grupoSemillero').value?.id ? editForm.get('grupoSemillero').value : grupoSemilleroOption" *ngFor="let grupoSemilleroOption of gruposemilleros; trackBy: trackGrupoSemilleroById">{{grupoSemilleroOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.facultad" for="field_facultad">Facultad</label>
                    <select class="form-control" id="field_facultad" name="facultad" formControlName="facultad">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="facultadOption.id === editForm.get('facultad').value?.id ? editForm.get('facultad').value : facultadOption" *ngFor="let facultadOption of facultads; trackBy: trackFacultadById">{{facultadOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.proyecto.modalidadDeGrado" for="field_modalidadDeGrado">Modalidad De Grado</label>
                    <select class="form-control" id="field_modalidadDeGrado" name="modalidadDeGrado" formControlName="modalidadDeGrado">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="modalidadDeGradoOption.id === editForm.get('modalidadDeGrado').value?.id ? editForm.get('modalidadDeGrado').value : modalidadDeGradoOption" *ngFor="let modalidadDeGradoOption of modalidaddegrados; trackBy: trackModalidadDeGradoById">{{modalidadDeGradoOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/proyecto/proyecto-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.proyecto.home.createOrEditLabel" v-text="$t('ciecytApp.proyecto.home.createOrEditLabel')">Create or edit a Proyecto</h2>
                <div>
                    <div class="form-group" v-if="proyecto.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="proyecto.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.titulo')" for="proyecto-titulo">Titulo</label>
                        <input type="text" class="form-control" name="titulo" id="proyecto-titulo"
                            :class="{'valid': !$v.proyecto.titulo.$invalid, 'invalid': $v.proyecto.titulo.$invalid }" v-model="$v.proyecto.titulo.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.url')" for="proyecto-url">Url</label>
                        <input type="text" class="form-control" name="url" id="proyecto-url"
                            :class="{'valid': !$v.proyecto.url.$invalid, 'invalid': $v.proyecto.url.$invalid }" v-model="$v.proyecto.url.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.lugarEjecucion')" for="proyecto-lugarEjecucion">Lugar Ejecucion</label>
                        <input type="text" class="form-control" name="lugarEjecucion" id="proyecto-lugarEjecucion"
                            :class="{'valid': !$v.proyecto.lugarEjecucion.$invalid, 'invalid': $v.proyecto.lugarEjecucion.$invalid }" v-model="$v.proyecto.lugarEjecucion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.duracion')" for="proyecto-duracion">Duracion</label>
                        <input type="text" class="form-control" name="duracion" id="proyecto-duracion"
                            :class="{'valid': !$v.proyecto.duracion.$invalid, 'invalid': $v.proyecto.duracion.$invalid }" v-model="$v.proyecto.duracion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.fechaIni')" for="proyecto-fechaIni">Fecha Ini</label>
                        <div class="input-group">
                            <input id="proyecto-fechaIni" type="date" class="form-control" name="fechaIni"  :class="{'valid': !$v.proyecto.fechaIni.$invalid, 'invalid': $v.proyecto.fechaIni.$invalid }"
                            v-model="$v.proyecto.fechaIni.$model"  />
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.fechaFin')" for="proyecto-fechaFin">Fecha Fin</label>
                        <div class="input-group">
                            <input id="proyecto-fechaFin" type="date" class="form-control" name="fechaFin"  :class="{'valid': !$v.proyecto.fechaFin.$invalid, 'invalid': $v.proyecto.fechaFin.$invalid }"
                            v-model="$v.proyecto.fechaFin.$model"  />
                        </div>
                    </div>
                   <!-- <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.contrapartidaPesos')" for="proyecto-contrapartidaPesos">Contrapartida Pesos</label>
                        <input type="number" class="form-control" name="contrapartidaPesos" id="proyecto-contrapartidaPesos"
                            :class="{'valid': !$v.proyecto.contrapartidaPesos.$invalid, 'invalid': $v.proyecto.contrapartidaPesos.$invalid }" v-model.number="$v.proyecto.contrapartidaPesos.$model" />
                    </div>
                    -->
                    <!--
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.contrapartidaEspecie')" for="proyecto-contrapartidaEspecie">Contrapartida Especie</label>
                        <input type="number" class="form-control" name="contrapartidaEspecie" id="proyecto-contrapartidaEspecie"
                            :class="{'valid': !$v.proyecto.contrapartidaEspecie.$invalid, 'invalid': $v.proyecto.contrapartidaEspecie.$invalid }" v-model.number="$v.proyecto.contrapartidaEspecie.$model" />
                    </div>-->
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.palabrasClave')" for="proyecto-palabrasClave">Palabras Clave</label>
                        <input type="text" class="form-control" name="palabrasClave" id="proyecto-palabrasClave"
                            :class="{'valid': !$v.proyecto.palabrasClave.$invalid, 'invalid': $v.proyecto.palabrasClave.$invalid }" v-model="$v.proyecto.palabrasClave.$model" />
                    </div>
                    <!--
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.proyecto.convocatoria')" for="proyecto-convocatoria">Convocatoria</label>
                        <input type="text" class="form-control" name="convocatoria" id="proyecto-convocatoria"
                            :class="{'valid': !$v.proyecto.convocatoria.$invalid, 'invalid': $v.proyecto.convocatoria.$invalid }" v-model="$v.proyecto.convocatoria.$model" />
                    </div>
                    -->
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.proyecto.proyectoLineaInvestigacion')" for="proyecto-proyectoLineaInvestigacion">Proyecto Linea Investigacion</label>
                        <select class="form-control" id="proyecto-proyectoLineaInvestigacion" name="proyectoLineaInvestigacion" v-model="proyecto.proyectoLineaInvestigacionId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="lineaInvestigacionOption.id" v-for="lineaInvestigacionOption in lineaInvestigacions" :key="lineaInvestigacionOption.id">{{lineaInvestigacionOption.linea}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.proyecto.proyectoGrupoSemillero')" for="proyecto-proyectoGrupoSemillero">Proyecto Grupo Semillero</label>
                        <select class="form-control" id="proyecto-proyectoGrupoSemillero" name="proyectoGrupoSemillero" v-model="proyecto.proyectoGrupoSemilleroId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="grupoSemilleroOption.id" v-for="grupoSemilleroOption in grupoSemilleros" :key="grupoSemilleroOption.id">{{grupoSemilleroOption.nombre}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.proyecto.proyectoModalidad')" for="proyecto-proyectoModalidad">Proyecto Modalidad</label>
                        <select class="form-control" id="proyecto-proyectoModalidad" name="proyectoModalidad" v-model="proyecto.proyectoModalidadId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="modalidadOption.id" v-for="modalidadOption in modalidads" :key="modalidadOption.id">{{modalidadOption.modalidad}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.proyecto.facultad')" for="proyecto-facultad">Facultad</label>
                        <select class="form-control" id="proyecto-facultad" name="facultad" v-model="proyecto.facultadId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="facultadOption.id" v-for="facultadOption in facultads" :key="facultadOption.id">{{facultadOption.id}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.proyecto.subLineaLineaInvestigacion')" for="proyecto-subLineaLineaInvestigacion">Sub Linea Linea Investigacion</label>
                        <select class="form-control" id="proyecto-subLineaLineaInvestigacion" name="subLineaLineaInvestigacion" v-model="proyecto.subLineaLineaInvestigacionId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="lineaInvestigacionOption.id" v-for="lineaInvestigacionOption in lineaInvestigacions" :key="lineaInvestigacionOption.id">{{lineaInvestigacionOption.linea}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.proyecto.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./proyecto-update.component.ts">
</script>
