// src/main/webapp/app/entities/presupuesto-valor/presupuesto-valor-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.presupuestoValor.home.createOrEditLabel" v-text="$t('ciecytApp.presupuestoValor.home.createOrEditLabel')">Create or edit a PresupuestoValor</h2>
                <div>
                    <div class="form-group" v-if="presupuestoValor.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="presupuestoValor.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.descripcion')" for="presupuesto-valor-descripcion">Descripcion</label>
                        <input type="text" class="form-control" name="descripcion" id="presupuesto-valor-descripcion"
                            :class="{'valid': !$v.presupuestoValor.descripcion.$invalid, 'invalid': $v.presupuestoValor.descripcion.$invalid }" v-model="$v.presupuestoValor.descripcion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.justificacion')" for="presupuesto-valor-justificacion">Justificacion</label>
                        <input type="text" class="form-control" name="justificacion" id="presupuesto-valor-justificacion"
                            :class="{'valid': !$v.presupuestoValor.justificacion.$invalid, 'invalid': $v.presupuestoValor.justificacion.$invalid }" v-model="$v.presupuestoValor.justificacion.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.cantidad')" for="presupuesto-valor-cantidad">Cantidad</label>
                        <input type="number" class="form-control" name="cantidad" id="presupuesto-valor-cantidad"
                            :class="{'valid': !$v.presupuestoValor.cantidad.$invalid, 'invalid': $v.presupuestoValor.cantidad.$invalid }" v-model.number="$v.presupuestoValor.cantidad.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.valorUnitario')" for="presupuesto-valor-valorUnitario">Valor Unitario</label>
                        <input type="number" class="form-control" name="valorUnitario" id="presupuesto-valor-valorUnitario"
                            :class="{'valid': !$v.presupuestoValor.valorUnitario.$invalid, 'invalid': $v.presupuestoValor.valorUnitario.$invalid }" v-model.number="$v.presupuestoValor.valorUnitario.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.especie')" for="presupuesto-valor-especie">Especie</label>
                        <input type="number" class="form-control" name="especie" id="presupuesto-valor-especie"
                            :class="{'valid': !$v.presupuestoValor.especie.$invalid, 'invalid': $v.presupuestoValor.especie.$invalid }" v-model.number="$v.presupuestoValor.especie.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.dinero')" for="presupuesto-valor-dinero">Dinero</label>
                        <input type="number" class="form-control" name="dinero" id="presupuesto-valor-dinero"
                            :class="{'valid': !$v.presupuestoValor.dinero.$invalid, 'invalid': $v.presupuestoValor.dinero.$invalid }" v-model.number="$v.presupuestoValor.dinero.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.presupuestoValor.ordenVista')" for="presupuesto-valor-ordenVista">Orden Vista</label>
                        <input type="number" class="form-control" name="ordenVista" id="presupuesto-valor-ordenVista"
                            :class="{'valid': !$v.presupuestoValor.ordenVista.$invalid, 'invalid': $v.presupuestoValor.ordenVista.$invalid }" v-model.number="$v.presupuestoValor.ordenVista.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.presupuestoValor.presupuestoValorRubro')" for="presupuesto-valor-presupuestoValorRubro">Presupuesto Valor Rubro</label>
                        <select class="form-control" id="presupuesto-valor-presupuestoValorRubro" name="presupuestoValorRubro" v-model="presupuestoValor.presupuestoValorRubroId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="rubroOption.id" v-for="rubroOption in rubros" :key="rubroOption.id">{{rubroOption.rubro}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.presupuestoValor.presupuestoValorProyecto')" for="presupuesto-valor-presupuestoValorProyecto">Presupuesto Valor Proyecto</label>
                        <select class="form-control" id="presupuesto-valor-presupuestoValorProyecto" name="presupuestoValorProyecto" v-model="presupuestoValor.presupuestoValorProyectoId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="proyectoOption.id" v-for="proyectoOption in proyectos" :key="proyectoOption.id">{{proyectoOption.titulo}}</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-bind:value="$t('ciecytApp.presupuestoValor.presupuestoValorEntidad')" for="presupuesto-valor-presupuestoValorEntidad">Presupuesto Valor Entidad</label>
                        <select class="form-control" id="presupuesto-valor-presupuestoValorEntidad" name="presupuestoValorEntidad" v-model="presupuestoValor.presupuestoValorEntidadId">
                            <option v-bind:value="null"></option>
                            <option v-bind:value="entidadOption.id" v-for="entidadOption in entidads" :key="entidadOption.id">{{entidadOption.entidad}}</option>
                        </select>
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.presupuestoValor.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./presupuesto-valor-update.component.ts">
</script>

// src/main/webapp/app/entities/presupuesto-valor/presupuesto-valor-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { JhiAlertService } from 'ng-jhipster';
import { IPresupuestoValor, PresupuestoValor } from 'app/shared/model/presupuesto-valor.model';
import { PresupuestoValorService } from './presupuesto-valor.service';
import { IProyecto } from 'app/shared/model/proyecto.model';
import { ProyectoService } from 'app/entities/proyecto';
import { IRubros } from 'app/shared/model/rubros.model';
import { RubrosService } from 'app/entities/rubros';

@Component({
  selector: 'jhi-presupuesto-valor-update',
  templateUrl: './presupuesto-valor-update.component.html'
})
export class PresupuestoValorUpdateComponent implements OnInit {
  presupuestoValor: IPresupuestoValor;
  isSaving: boolean;

  proyectos: IProyecto[];

  rubros: IRubros[];

  editForm = this.fb.group({
    id: [],
    descripcion: [],
    justificacion: [],
    cantidad: [],
    valorUnitario: [],
    especie: [],
    dinero: [],
    entidadFinanciadora: [],
    proyecto: [],
    rubros: []
  });

  constructor(
    protected jhiAlertService: JhiAlertService,
    protected presupuestoValorService: PresupuestoValorService,
    protected proyectoService: ProyectoService,
    protected rubrosService: RubrosService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ presupuestoValor }) => {
      this.updateForm(presupuestoValor);
      this.presupuestoValor = presupuestoValor;
    });
    this.proyectoService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IProyecto[]>) => mayBeOk.ok),
        map((response: HttpResponse<IProyecto[]>) => response.body)
      )
      .subscribe((res: IProyecto[]) => (this.proyectos = res), (res: HttpErrorResponse) => this.onError(res.message));
    this.rubrosService
      .query()
      .pipe(
        filter((mayBeOk: HttpResponse<IRubros[]>) => mayBeOk.ok),
        map((response: HttpResponse<IRubros[]>) => response.body)
      )
      .subscribe((res: IRubros[]) => (this.rubros = res), (res: HttpErrorResponse) => this.onError(res.message));
  }

  updateForm(presupuestoValor: IPresupuestoValor) {
    this.editForm.patchValue({
      id: presupuestoValor.id,
      descripcion: presupuestoValor.descripcion,
      justificacion: presupuestoValor.justificacion,
      cantidad: presupuestoValor.cantidad,
      valorUnitario: presupuestoValor.valorUnitario,
      especie: presupuestoValor.especie,
      dinero: presupuestoValor.dinero,
      entidadFinanciadora: presupuestoValor.entidadFinanciadora,
      proyecto: presupuestoValor.proyecto,
      rubros: presupuestoValor.rubros
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const presupuestoValor = this.createFromForm();
    if (presupuestoValor.id !== undefined) {
      this.subscribeToSaveResponse(this.presupuestoValorService.update(presupuestoValor));
    } else {
      this.subscribeToSaveResponse(this.presupuestoValorService.create(presupuestoValor));
    }
  }

  private createFromForm(): IPresupuestoValor {
    const entity = {
      ...new PresupuestoValor(),
      id: this.editForm.get(['id']).value,
      descripcion: this.editForm.get(['descripcion']).value,
      justificacion: this.editForm.get(['justificacion']).value,
      cantidad: this.editForm.get(['cantidad']).value,
      valorUnitario: this.editForm.get(['valorUnitario']).value,
      especie: this.editForm.get(['especie']).value,
      dinero: this.editForm.get(['dinero']).value,
      entidadFinanciadora: this.editForm.get(['entidadFinanciadora']).value,
      proyecto: this.editForm.get(['proyecto']).value,
      rubros: this.editForm.get(['rubros']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPresupuestoValor>>) {
    result.subscribe((res: HttpResponse<IPresupuestoValor>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
  protected onError(errorMessage: string) {
    this.jhiAlertService.error(errorMessage, null, null);
  }

  trackProyectoById(index: number, item: IProyecto) {
    return item.id;
  }

  trackRubrosById(index: number, item: IRubros) {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-presupuesto-valor-heading" jhiTranslate="ciecytApp.presupuestoValor.home.createOrEditLabel">Create or edit a Presupuesto Valor</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!presupuestoValor.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.descripcion" for="field_descripcion">Descripcion</label>
                    <input type="text" class="form-control" name="descripcion" id="field_descripcion"
                           formControlName="descripcion"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.justificacion" for="field_justificacion">Justificacion</label>
                    <input type="text" class="form-control" name="justificacion" id="field_justificacion"
                           formControlName="justificacion"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.cantidad" for="field_cantidad">Cantidad</label>
                    <input type="number" class="form-control" name="cantidad" id="field_cantidad"
                           formControlName="cantidad"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.valorUnitario" for="field_valorUnitario">Valor Unitario</label>
                    <input type="number" class="form-control" name="valorUnitario" id="field_valorUnitario"
                           formControlName="valorUnitario"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.especie" for="field_especie">Especie</label>
                    <input type="number" class="form-control" name="especie" id="field_especie"
                           formControlName="especie"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.dinero" for="field_dinero">Dinero</label>
                    <input type="number" class="form-control" name="dinero" id="field_dinero"
                           formControlName="dinero"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.entidadFinanciadora" for="field_entidadFinanciadora">Entidad Financiadora</label>
                    <input type="text" class="form-control" name="entidadFinanciadora" id="field_entidadFinanciadora"
                           formControlName="entidadFinanciadora"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.proyecto" for="field_proyecto">Proyecto</label>
                    <select class="form-control" id="field_proyecto" name="proyecto" formControlName="proyecto">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="proyectoOption.id === editForm.get('proyecto').value?.id ? editForm.get('proyecto').value : proyectoOption" *ngFor="let proyectoOption of proyectos; trackBy: trackProyectoById">{{proyectoOption.id}}</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.presupuestoValor.rubros" for="field_rubros">Rubros</label>
                    <select class="form-control" id="field_rubros" name="rubros" formControlName="rubros">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="rubrosOption.id === editForm.get('rubros').value?.id ? editForm.get('rubros').value : rubrosOption" *ngFor="let rubrosOption of rubros; trackBy: trackRubrosById">{{rubrosOption.id}}</option>
                    </select>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
