// src/main/webapp/app/entities/tipo-pregunta/tipo-pregunta-update.vue
<template>
    <div class="row justify-content-center">
        <div class="col-8">
            <form name="editForm" role="form" novalidate v-on:submit.prevent="save()" >
                <h2 id="ciecytApp.tipoPregunta.home.createOrEditLabel" v-text="$t('ciecytApp.tipoPregunta.home.createOrEditLabel')">Create or edit a TipoPregunta</h2>
                <div>
                    <div class="form-group" v-if="tipoPregunta.id">
                        <label for="id" v-text="$t('global.field.id')">ID</label>
                        <input type="text" class="form-control" id="id" name="id"
                               v-model="tipoPregunta.id" readonly />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.tipoPregunta.tipoPregunta')" for="tipo-pregunta-tipoPregunta">Tipo Pregunta</label>
                        <input type="text" class="form-control" name="tipoPregunta" id="tipo-pregunta-tipoPregunta"
                            :class="{'valid': !$v.tipoPregunta.tipoPregunta.$invalid, 'invalid': $v.tipoPregunta.tipoPregunta.$invalid }" v-model="$v.tipoPregunta.tipoPregunta.$model" />
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" v-text="$t('ciecytApp.tipoPregunta.tipoDato')" for="tipo-pregunta-tipoDato">Tipo Dato</label>
                        <input type="text" class="form-control" name="tipoDato" id="tipo-pregunta-tipoDato"
                            :class="{'valid': !$v.tipoPregunta.tipoDato.$invalid, 'invalid': $v.tipoPregunta.tipoDato.$invalid }" v-model="$v.tipoPregunta.tipoDato.$model" />
                    </div>
                </div>
                <div>
                    <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
                        <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
                    </button>
                    <button type="submit" id="save-entity" :disabled="$v.tipoPregunta.$invalid || isSaving" class="btn btn-primary">
                        <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</template>
<script lang="ts" src="./tipo-pregunta-update.component.ts">
</script>

// src/main/webapp/app/entities/tipo-pregunta/tipo-pregunta-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { ITipoPregunta, TipoPregunta } from 'app/shared/model/tipo-pregunta.model';
import { TipoPreguntaService } from './tipo-pregunta.service';

@Component({
  selector: 'jhi-tipo-pregunta-update',
  templateUrl: './tipo-pregunta-update.component.html'
})
export class TipoPreguntaUpdateComponent implements OnInit {
  tipoPregunta: ITipoPregunta;
  isSaving: boolean;

  editForm = this.fb.group({
    id: [],
    tipoPregunta: [],
    tipoDato: []
  });

  constructor(protected tipoPreguntaService: TipoPreguntaService, protected activatedRoute: ActivatedRoute, private fb: FormBuilder) {}

  ngOnInit() {
    this.isSaving = false;
    this.activatedRoute.data.subscribe(({ tipoPregunta }) => {
      this.updateForm(tipoPregunta);
      this.tipoPregunta = tipoPregunta;
    });
  }

  updateForm(tipoPregunta: ITipoPregunta) {
    this.editForm.patchValue({
      id: tipoPregunta.id,
      tipoPregunta: tipoPregunta.tipoPregunta,
      tipoDato: tipoPregunta.tipoDato
    });
  }

  previousState() {
    window.history.back();
  }

  save() {
    this.isSaving = true;
    const tipoPregunta = this.createFromForm();
    if (tipoPregunta.id !== undefined) {
      this.subscribeToSaveResponse(this.tipoPreguntaService.update(tipoPregunta));
    } else {
      this.subscribeToSaveResponse(this.tipoPreguntaService.create(tipoPregunta));
    }
  }

  private createFromForm(): ITipoPregunta {
    const entity = {
      ...new TipoPregunta(),
      id: this.editForm.get(['id']).value,
      tipoPregunta: this.editForm.get(['tipoPregunta']).value,
      tipoDato: this.editForm.get(['tipoDato']).value
    };
    return entity;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITipoPregunta>>) {
    result.subscribe((res: HttpResponse<ITipoPregunta>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
  }

  protected onSaveSuccess() {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError() {
    this.isSaving = false;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-tipo-pregunta-heading" jhiTranslate="ciecytApp.tipoPregunta.home.createOrEditLabel">Create or edit a Tipo Pregunta</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!tipoPregunta.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id"
                        readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.tipoPregunta.tipoPregunta" for="field_tipoPregunta">Tipo Pregunta</label>
                    <input type="text" class="form-control" name="tipoPregunta" id="field_tipoPregunta"
                           formControlName="tipoPregunta"/>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="ciecytApp.tipoPregunta.tipoDato" for="field_tipoDato">Tipo Dato</label>
                    <input type="text" class="form-control" name="tipoDato" id="field_tipoDato"
                           formControlName="tipoDato"/>
                </div>

            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
